import React, { useEffect, useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { CalendarDays, Plus, X } from 'lucide-react';
import type { Account, Card, Category, CreateMoneyMovementInput, MoneyMovement, MoneyMovementType, User } from '../../types/index.js';
import { ApiService } from '../../services/api.js';
import { calculateMovementTotals, MOVEMENT_LABELS } from '../../domain/moneyMovements.js';

interface EntradasProps { householdId: string; currentUser: User; accounts: Account[]; cards: Card[]; categories: Category[]; onRefresh: () => void; }
type Segment = 'income' | 'movement' | 'loan';
const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const colors: Record<MoneyMovementType, string> = { income: 'bg-emerald-500/15 text-emerald-300', transfer: 'bg-blue-500/15 text-blue-300', investment_deposit: 'bg-violet-500/15 text-violet-300', investment_withdrawal: 'bg-cyan-500/15 text-cyan-300', invoice_payment: 'bg-amber-500/15 text-amber-300', loan_disbursement: 'bg-rose-500/15 text-rose-300' };
const today = new Date().toISOString().slice(0, 10);

export const Entradas: React.FC<EntradasProps> = ({ householdId, currentUser, accounts, cards, categories, onRefresh }) => {
  const [segment, setSegment] = useState<Segment>('income');
  const [movements, setMovements] = useState<MoneyMovement[]>([]);
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const incomeCategories = categories.filter((category) => category.type === 'income');
  const bankAccounts = accounts.filter((account) => account.account_type !== 'investment');
  const investments = accounts.filter((account) => account.account_type === 'investment');
  const initial = (): CreateMoneyMovementInput => ({ type: segment === 'loan' ? 'loan_disbursement' : segment === 'income' ? 'income' : 'transfer', amount: 0, description: '', beneficiary_user_id: currentUser.id, destination_account_id: bankAccounts[0]?.id, category_id: incomeCategories[0]?.id, competence_month: today.slice(0, 7), movement_date: today, status: 'realized', loan: segment === 'loan' ? { lender: '', installment_count: 12, first_due_date: today } : null });
  const [form, setForm] = useState<CreateMoneyMovementInput>(initial);
  const load = async () => setMovements((await ApiService.getMoneyMovements(householdId, currentUser.id)).movements);
  useEffect(() => { void load(); }, [householdId, currentUser.id]);
  const totals = useMemo(() => calculateMovementTotals(movements), [movements]);
  const visible = movements.filter((item) => segment === 'income' ? item.type === 'income' : segment === 'loan' ? item.type === 'loan_disbursement' : !['income', 'loan_disbursement'].includes(item.type));
  const changeType = (type: MoneyMovementType) => setForm((value) => ({ ...value, type, source_account_id: type === 'investment_withdrawal' ? investments[0]?.id : bankAccounts[0]?.id, destination_account_id: type === 'investment_deposit' ? investments[0]?.id : bankAccounts[0]?.id }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await ApiService.createMoneyMovement(householdId, currentUser.id, form); await load(); onRefresh(); setOpen(false); setForm(initial()); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : 'Não foi possível salvar.'); } finally { setBusy(false); } };
  const openForm = () => { setForm(initial()); setError(''); setOpen(true); };

  return <div className="space-y-5 pb-28 text-slate-100">
    <header className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-black">Entradas e movimentações</h1><p className="mt-1 text-xs text-slate-400">Resultado, circulação de dinheiro e obrigações sem dupla contagem.</p></div><button onClick={openForm} className="min-h-11 shrink-0 rounded-2xl bg-emerald-600 px-3 text-xs font-bold"><Plus className="mr-1 inline h-4 w-4"/>Registrar</button></header>
    <div className="grid grid-cols-2 gap-2">
      <Metric label="Receitas recebidas" value={totals.realizedIncome} tone="emerald"/><Metric label="Receitas previstas" value={totals.projectedIncome} tone="blue"/><Metric label="Movimentado (não receita)" value={totals.internalMovements} tone="violet"/><Metric label="Empréstimos recebidos" value={totals.loansReceived} tone="rose"/>
    </div>
    <div className="grid grid-cols-3 rounded-2xl bg-slate-900 p-1" role="tablist">{([['income','Receitas reais'],['movement','Movimentações'],['loan','Empréstimos']] as const).map(([id,label]) => <button key={id} onClick={() => setSegment(id)} className={`min-h-11 rounded-xl px-2 text-[11px] font-bold ${segment === id ? 'bg-slate-700 text-white' : 'text-slate-400'}`}>{label}</button>)}</div>
    <div className="space-y-2">{visible.length === 0 && <div className="rounded-3xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-500">Nenhum registro neste grupo.</div>}{visible.map((item) => <motion.article initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4"><div className="flex justify-between gap-3"><div><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-extrabold ${colors[item.type]}`}>{MOVEMENT_LABELS[item.type]}</span><h2 className="mt-2 text-sm font-bold">{item.description}</h2><p className="mt-1 text-[11px] text-slate-400"><CalendarDays className="mr-1 inline h-3 w-3"/>{item.movement_date} · competência {item.competence_month} · {item.status === 'realized' ? 'Efetivado' : 'Previsto'}</p>{item.effective_funder_user_id && <p className="mt-1 text-[10px] text-amber-300">Financiador efetivo: titular da conta de origem</p>}{item.loan && <p className="mt-1 text-[10px] text-rose-300">{item.loan.installment_count} compromissos projetados · credor {item.loan.lender}</p>}</div><strong className="text-sm">{money(item.amount)}</strong></div></motion.article>)}</div>
    <AnimatePresence>{open && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 flex items-end bg-black/70 sm:items-center sm:justify-center"><motion.form initial={{y:40}} animate={{y:0}} onSubmit={submit} className="max-h-[92dvh] w-full max-w-md overflow-y-auto rounded-t-[32px] bg-slate-900 p-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] sm:rounded-[32px]"><div className="mb-5 flex justify-between"><div><h2 className="text-lg font-black">Novo registro</h2><p className="text-xs text-slate-400">{segment === 'income' ? 'Receita real' : segment === 'loan' ? 'Contrato e entrada do recurso' : 'Movimento sem efeito em receitas'}</p></div><button type="button" onClick={() => setOpen(false)} className="h-11 w-11 rounded-full bg-slate-800"><X className="mx-auto h-5 w-5"/></button></div>
      {segment === 'movement' && <Field label="Tipo"><select value={form.type} onChange={(e) => changeType(e.target.value as MoneyMovementType)}><option value="transfer">Transferência conta a conta</option><option value="investment_deposit">Aporte em investimento</option><option value="investment_withdrawal">Resgate de investimento</option><option value="invoice_payment">Pagamento de fatura</option></select></Field>}
      <div className="grid grid-cols-2 gap-3"><Field label="Valor"><input inputMode="decimal" required min="0.01" step="0.01" type="number" value={form.amount || ''} onChange={(e) => setForm({...form, amount:Number(e.target.value)})}/></Field><Field label="Data"><input required type="date" value={form.movement_date} onChange={(e) => setForm({...form,movement_date:e.target.value})}/></Field></div>
      <Field label="Descrição / origem"><input required value={form.description} placeholder="Ex.: salário, PLR, aluguel" onChange={(e) => setForm({...form,description:e.target.value})}/></Field>
      {segment === 'income' && <><Field label="Beneficiário"><select value={form.beneficiary_user_id ?? ''} onChange={(e) => setForm({...form,beneficiary_user_id:e.target.value})}><option value={currentUser.id}>{currentUser.name}</option><option value="usr-wallace-001">Wallace</option><option value="usr-guilherme-002">Guilherme</option></select></Field><Field label="Categoria"><select value={form.category_id ?? ''} onChange={(e) => setForm({...form,category_id:e.target.value})}>{incomeCategories.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></>}
      {(form.type === 'transfer' || form.type === 'investment_deposit' || form.type === 'investment_withdrawal' || form.type === 'invoice_payment') && <Field label={form.type === 'investment_withdrawal' ? 'Investimento de origem' : 'Conta de origem'}><AccountSelect accounts={form.type === 'investment_withdrawal' ? investments : bankAccounts} value={form.source_account_id} onChange={(id)=>setForm({...form,source_account_id:id})}/></Field>}
      {form.type !== 'invoice_payment' && <Field label={form.type === 'investment_deposit' ? 'Investimento de destino' : 'Conta de destino'}><AccountSelect accounts={form.type === 'investment_deposit' ? investments : bankAccounts} value={form.destination_account_id} onChange={(id)=>setForm({...form,destination_account_id:id})}/></Field>}
      {form.type === 'invoice_payment' && <Field label="Fatura liquidada"><select required value={`${form.card_id ?? ''}|${form.invoice_reference ?? ''}`} onChange={(e)=>{const [card_id,invoice_reference]=e.target.value.split('|');setForm({...form,card_id,invoice_reference})}}><option value="">Selecione cartão e competência</option>{cards.map((card)=><option key={card.id} value={`${card.id}|${form.competence_month}`}>{card.name} · {form.competence_month}</option>)}</select></Field>}
      {segment === 'loan' && <div className="grid grid-cols-2 gap-3"><Field label="Credor"><input required value={form.loan?.lender ?? ''} onChange={(e)=>setForm({...form,loan:{...form.loan!,lender:e.target.value}})}/></Field><Field label="Parcelas"><input required type="number" min="1" max="360" value={form.loan?.installment_count} onChange={(e)=>setForm({...form,loan:{...form.loan!,installment_count:Number(e.target.value)}})}/></Field><Field label="1º vencimento"><input required type="date" value={form.loan?.first_due_date} onChange={(e)=>setForm({...form,loan:{...form.loan!,first_due_date:e.target.value}})}/></Field></div>}
      <div className="grid grid-cols-2 gap-3"><Field label="Competência"><input required type="month" value={form.competence_month} onChange={(e)=>setForm({...form,competence_month:e.target.value})}/></Field><Field label="Status"><select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value as 'projected'|'realized'})}><option value="realized">Recebido / efetivado</option><option value="projected">Previsto</option></select></Field></div>
      <Field label="Observação"><textarea rows={2} value={form.notes ?? ''} onChange={(e)=>setForm({...form,notes:e.target.value})}/></Field>{error && <p className="mb-3 rounded-xl bg-rose-950 p-3 text-xs text-rose-300">{error}</p>}<button disabled={busy} className="min-h-12 w-full rounded-2xl bg-emerald-600 font-bold disabled:opacity-50">{busy?'Salvando…':'Salvar no ledger'}</button>
    </motion.form></motion.div>}</AnimatePresence>
  </div>;
};
const Metric = ({label,value,tone}:{label:string;value:number;tone:string}) => <div className={`rounded-2xl border border-${tone}-500/20 bg-slate-900 p-3`}><p className="text-[10px] text-slate-400">{label}</p><strong className="mt-1 block text-sm">{money(value)}</strong></div>;
const Field = ({label,children}:{label:string;children:React.ReactNode}) => <label className="mb-3 block text-[11px] font-bold text-slate-300">{label}<div className="mt-1 [&>*]:min-h-11 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-slate-700 [&>*]:bg-slate-950 [&>*]:px-3 [&>*]:text-sm">{children}</div></label>;
const AccountSelect = ({accounts,value,onChange}:{accounts:Account[];value?:string|null;onChange:(id:string)=>void}) => <select required value={value ?? ''} onChange={(e)=>onChange(e.target.value)}><option value="">Selecione</option>{accounts.map((item)=><option key={item.id} value={item.id}>{item.name} · {money(item.current_balance)}</option>)}</select>;
