import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{test}from'node:test';
const serviceSource=await readFile(new URL('./financialDashboard.ts',import.meta.url),'utf8');const screenSource=await readFile(new URL('../components/app/CasaHomeScreen.tsx',import.meta.url),'utf8');const statementSource=await readFile(new URL('../components/app/MonthlyPositionStatement.tsx',import.meta.url),'utf8');const periodSource=await readFile(new URL('../components/app/FinancialPeriodNavigator.tsx',import.meta.url),'utf8');const selectorSource=await readFile(new URL('../components/app/FinancialPerspectiveSelector.tsx',import.meta.url),'utf8');const prioritySource=await readFile(new URL('../components/app/FinancialPriorityCenter.tsx',import.meta.url),'utf8');const settlementHubSource=await readFile(new URL('../components/app/SettlementHub.tsx',import.meta.url),'utf8');const productSpec=await readFile(new URL('../../docs/product-spec-v2.md',import.meta.url),'utf8');
test('Casa home keeps the human story and unified financial map',()=>{const householdView=screenSource;for(const label of ['Como estamos?','Entre vocês','<FinancialPriorityCenter','<UpcomingFinancialEvents','HomeFinancialMap','Olhando pra frente'])assert.match(householdView,new RegExp(label.replace(/[?]/g,'\\?')));assert.match(prioritySource,/Precisa de atenção/);assert.match(settlementHubSource,/Valores com pessoas/);});
test('benefit resources count as available money while investments remain separate',()=>{assert.match(serviceSource,/if\(row\.is_investment\)summary\.investments\+=amount;/);assert.match(serviceSource,/else if\(row\.type==='meal_benefit'\)\{summary\.benefits\+=amount;summary\.availableCash\+=amount;/);});
test('dashboard reads canonical health, prioritized attention and four-month projection',()=>{assert.match(serviceSource,/rpc\('financial_household_health_position'/);assert.match(serviceSource,/from\('financial_projection_confidence_positions'\)/);assert.match(serviceSource,/rpc\('financial_priority_attention_items'/);assert.match(serviceSource,/rpc\('financial_monthly_projection'/);assert.match(serviceSource,/p_horizon_months\s*:\s*4/);assert.match(serviceSource,/rpc\('financial_liquidity_guidance'/);});
test('member selector uses canonical individual projection',()=>{assert.match(screenSource,/FinancialPerspectiveSelector/);assert.match(selectorSource,/Nossa Casa/);assert.match(screenSource,/getMemberFinancialPerspective/);assert.match(serviceSource,/rpc\('financial_member_monthly_projection'/);assert.match(serviceSource,/p_member_id\s*:\s*memberId/);assert.doesNotMatch(screenSource,/available_money\s*\/\s*2|projected_balance\s*\/\s*2/);});
test('individual perspective keeps liquidity responsibility and funding distinct',()=>{for(const value of['opening_liquidity','Minha responsabilidade econômica restante','economic_responsibility_remaining','projected_funding_remaining','SettlementHub','MonthlyPositionStatement'])assert.match(screenSource,new RegExp(value));assert.match(screenSource,/currentAvailable=\{Number\(current\.opening_liquidity\)\}/);});
test('failed individual read is not silently replaced',()=>{assert.match(serviceSource,/unattributed_funding_remaining/);assert.match(screenSource,/memberError/);assert.match(screenSource,/Nenhum valor foi substituído por zero/);});
test('Casa keeps current cash and projected closing inside the human summary',()=>{assert.match(screenSource,/currentAvailable=\{currentCash\}/);assert.match(screenSource,/MonthlyPositionStatement/);assert.match(screenSource,/currentMonth\.projected_ending_cash/);assert.match(statementSource,/subjectLabel/);for(const value of['Estamos tranquilos neste mês','pode terminar o mês com','Ainda entra','Ainda sai','A projeção combina o que já aconteceu com os compromissos ainda previstos'])assert.match(statementSource,new RegExp(value));});
test('monthly indicators use true income and commitments',()=>{for(const value of['realized_true_income_in_month','expected_reliable_income_remaining','realized_commitments_in_month','remaining_commitments_in_month','projected_recurring_commitments','prior_pending_outflow'])assert.match(screenSource,new RegExp(value));});
test('money classes follow the unified Home financial map',async()=>{const map=await readFile(new URL('../components/app/HomeFinancialMap.tsx',import.meta.url),'utf8');for(const value of ["label:'Contas'","label:'Dinheiro'","label:'Benefícios'","label:'Investimentos e reservas'"])assert.match(map,new RegExp(value));assert.match(map,/>Contas</);assert.match(map,/>Cartões</);assert.match(map,/>Outras pessoas</);});
test('dashboard stays read-only',()=>{assert.doesNotMatch(serviceSource,/\.insert\(|\.update\(|\.delete\(|\.upsert\(/);for(const rpc of['financial_household_health_position','financial_priority_attention_items','financial_monthly_projection','financial_member_monthly_projection','financial_liquidity_guidance'])assert.match(serviceSource,new RegExp(`rpc\\('${rpc}'`));assert.doesNotMatch(serviceSource,/create_financial_transaction|settle_|refund_|correct_|cancel_/);});

test('individual perspective explains liquidity, projected change and household settlement visually',()=>{for(const value of['projected_ending_liquidity','MonthlyPositionStatement','Entre vocês','SettlementHub'])assert.match(screenSource,new RegExp(value));});

test('household forward view keeps considered flows and projected ending cash visible without turning into a report',()=>{
 assert.match(screenSource,/Olhando pra frente/);
 assert.match(screenSource,/Pode faltar dinheiro no fechamento|Deve fechar com/);
 assert.match(screenSource,/Ainda entra|futureExpectedIncome/);
 assert.match(screenSource,/Ainda sai|futureRemainingOutflow/);
 assert.match(screenSource,/realized_true_income_in_month/);
 assert.match(screenSource,/expected_reliable_income_remaining/);
 assert.match(screenSource,/remaining_commitments_in_month/);
 assert.match(screenSource,/projected_ending_cash/);
 assert.match(screenSource,/overflow-x-auto/);
});

test('Home financial map keeps card capacity contextual without treating credit as money',async()=>{const map=await readFile(new URL('../components/app/HomeFinancialMap.tsx',import.meta.url),'utf8');for(const value of ['Cartões','Neste mês','Próximos meses','Limite total','current_invoice_remaining','future_known_commitments','credit_limit'])assert.match(map,new RegExp(value));assert.match(map,/onOpenCard/);assert.match(map,/ratio/);assert.doesNotMatch(map,/cardExposure/);});

test('Casa month navigator opens a real monthly picker instead of resetting on center click',()=>{assert.match(screenSource,/FinancialPeriodNavigator/);assert.match(screenSource,/pickerTitle="Escolher mês da Casa"/);assert.match(periodSource,/type="month"/);assert.match(screenSource,/setPeriodPickerOpen\(value=>!value\)/);assert.match(screenSource,/setReferenceMonth\(normalizeReferenceMonth\(value\)\)/);assert.match(periodSource,/Mês atual/);});

test('normal recurring expense does not become attention before it is actually overdue',()=>{assert.match(serviceSource,/attention_type!=='recurring_expense_due'/);});
