import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const priority=await readFile(new URL('../../src/components/app/FinancialPriorityCenter.tsx',import.meta.url),'utf8');
const app=await readFile(new URL('../../src/components/app/CasaFinanceApp.tsx',import.meta.url),'utf8');
const intent=await readFile(new URL('../../src/finance/cardReviewIntent.ts',import.meta.url),'utf8');
const invoices=await readFile(new URL('../../src/components/app/InvoicesScreen.tsx',import.meta.url),'utf8');
test('over-limit attention preserves the canonical card identity',()=>{assert.match(priority,/attention_type==='card_over_limit'/);assert.match(priority,/entity_type==='card'/);assert.match(priority,/kind:'card-over-limit',cardId:item\.entity_id/);assert.match(priority,/Revisar este cartão/);});
test('Home only creates transient card review context',()=>{assert.match(app,/if\(action\.kind==='card-over-limit'\)\{setCardReviewIntent\(\{cardId:action\.cardId,source:'attention'\}\);setSelectedCardId\(action\.cardId\);setInvoiceModalOpen\(true\);return;\}/);assert.doesNotMatch(intent,/supabase|rpc|insert|update|delete|settle|transfer/i);});
test('card review rereads canonical card state and highlights only the exact card',()=>{assert.match(invoices,/listFinancialInvoices/);assert.match(invoices,/listCardOverviews/);assert.match(invoices,/cards\.some\(row=>row\.card_id===cardReviewIntent\.cardId\)/);assert.match(invoices,/cardReviewIntent\?\.cardId===card\.card_id/);assert.match(invoices,/cardReviewIntent\?\.cardId===row\.card_id/);});
test('review is read-only until the user explicitly chooses invoice payment',()=>{assert.doesNotMatch(intent,/pay|transfer|limit|supabase|rpc/i);assert.match(invoices,/nenhuma compra, pagamento ou mudança de limite foi feita/);assert.match(invoices,/onPay\?\.\(row\)/);const prePayment=invoices.slice(0,invoices.indexOf('onPay?.(row)'));assert.doesNotMatch(prePayment,/\.rpc\(|\.insert\(|\.update\(|\.delete\(/);});
