import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const html = fs.readFileSync(path.join(process.cwd(), 'index.html'), 'utf8');
const manifest = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), 'public/manifest.webmanifest'), 'utf8'),
) as { display?: string; start_url?: string; scope?: string };

test('mobile shell does not request the removed Express runtime config', () => {
  assert.doesNotMatch(html, /runtime-config\.js|generated by Express/i);
  assert.match(html, /<script type="module" src="\/src\/main\.tsx"><\/script>/);
});

test('iPhone/PWA shell keeps standalone mobile metadata', () => {
  assert.match(html, /apple-mobile-web-app-capable" content="yes"/);
  assert.match(html, /apple-mobile-web-app-status-bar-style" content="black-translucent"/);
  assert.match(html, /viewport-fit=cover/);
  assert.match(html, /rel="manifest" href="\/manifest\.webmanifest"/);
  assert.equal(manifest.display, 'standalone');
  assert.equal(manifest.start_url, '/');
  assert.equal(manifest.scope, '/');
});
