import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const priority=await readFile(new URL('../../src/components/app/FinancialPriorityCenter.tsx',import.meta.url),'utf8');
const app=await readFile(new URL('../../src/components/app/CasaFinanceApp.tsx',import.meta.url),'utf8');
const intent=await readFile(new URL('../../src/finance/accountReviewIntent.ts',import.meta.url),'utf8');
const settings=await readFile(new URL('../../src/components/app/SettingsScreen.tsx',import.meta.url),'utf8');
const setup=await readFile(new URL('../../src/components/auth/HouseholdFinancialSetup.tsx',import.meta.url),'utf8');
test('overdraft attention preserves exact canonical account identity',()=>{assert.match(priority,/attention_type==='overdraft_in_use'/);assert.match(priority,/entity_type==='account'/);assert.match(priority,/kind:'overdraft-account',accountId:item\.entity_id/);assert.match(priority,/Revisar esta conta/);});
test('Home creates only transient account review context',()=>{assert.match(app,/if\(action\.kind==='overdraft-account'\)\{setAccountReviewIntent\(\{accountId:action\.accountId,source:'overdraft'\}\);setScreen\('settings'\);return;\}/);assert.doesNotMatch(intent,/supabase|rpc|insert|update|delete|settle|transfer/i);});
test('settings opens exact current account after canonical reread',()=>{assert.match(settings,/consumeAccountReviewIntent/);assert.match(settings,/HouseholdFinancialSetup initialAccountId/);assert.match(setup,/listHouseholdFinancialAccounts/);assert.match(setup,/accounts\.some\(item=>item\.id===initialAccountId\)/);assert.match(setup,/initialAccountId===item\.id/);assert.match(setup,/LIS em uso/);});
test('overdraft review keeps debt separate from available cash and makes no movement',()=>{assert.match(setup,/limite do LIS continua sendo crédito\/dívida, não dinheiro disponível/);assert.match(setup,/Nada foi movimentado/);assert.doesNotMatch(intent,/supabase|\.rpc\(|\.insert\(|\.update\(|\.delete\(|settle|payment_event|money_movement/i);});
