import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { CreditCard, LoaderCircle } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { listCardRefundPositions, recordCardInvoiceCreditRefund, type CardRefundPosition } from '../../finance/cardRefunds.js';

const money=(value:number|string|null|undefined)=>Number(value??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const localDate=()=>{const now=new Date();const offset=now.getTimezoneOffset();return new Date(now.getTime()-offset*60_000).toISOString().slice(0,10);};
const normalizeAmount=(value:string)=>value.trim().replace(/\./g,'').replace(',','.');

export function CardRefundAction({initialTransactionId}:{initialTransactionId?:string}={}){
  const{household}=useSupabaseAuth();
  const[rows,setRows]=useState<CardRefundPosition[]>([]);const[selectedId,setSelectedId]=useState('');const[targetInvoiceId,setTargetInvoiceId]=useState('');const[amount,setAmount]=useState('');const[date,setDate]=useState(localDate());const[reason,setReason]=useState('Estorno/devolução no cartão');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[loadError,setLoadError]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[success,setSuccess]=useState<string|null>(null);
  const clearLoadedContext=()=>{setRows([]);setSelectedId('');setTargetInvoiceId('');setAmount('');};
  const load=async()=>{if(!supabase||!household)return;setLoading(true);setLoadError(null);setError(null);try{const nextRows=await listCardRefundPositions(supabase,household.id);setRows(initialTransactionId?nextRows.filter(row=>row.transaction_id===initialTransactionId):nextRows);}catch{clearLoadedContext();setLoadError('Não foi possível conferir as compras e faturas que ainda podem receber devolução. Nenhum crédito de estorno pode ser registrado até uma nova leitura válida.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[household?.id]);
  const selected=useMemo(()=>rows.find(row=>row.transaction_id===selectedId)??null,[rows,selectedId]);
  const target=useMemo(()=>selected?.eligible_invoice_targets.find(item=>item.invoice_id===targetInvoiceId)??null,[selected,targetInvoiceId]);
  useEffect(()=>{if(initialTransactionId&&rows.some(row=>row.transaction_id===initialTransactionId&&Number(row.remaining_refundable_amount)>0&&row.eligible_invoice_targets.length>0))setSelectedId(initialTransactionId);},[initialTransactionId,rows]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(loadError){setError('Confira novamente as compras e faturas antes de registrar a devolução.');return;}if(loading){setError('Aguarde a conferência terminar antes de registrar a devolução.');return;}if(!supabase||!household||!selected||!target)return;const normalized=normalizeAmount(amount);const numeric=Number(normalized);const max=Math.min(Number(selected.remaining_refundable_amount),Number(target.commitment_amount),Number(target.invoice_outstanding));if(!Number.isFinite(numeric)||numeric<=0||numeric>max){setError(`Informe um valor entre R$ 0,01 e ${money(max)}.`);return;}if(!reason.trim()){setError('Informe o motivo da devolução.');return;}setSaving(true);setError(null);setSuccess(null);try{await recordCardInvoiceCreditRefund(supabase,{householdId:household.id,transactionId:selected.transaction_id,targetInvoiceId:target.invoice_id,amount:normalized,occurredAt:`${date}T12:00:00-03:00`,reason});setSuccess('Devolução registrada. O Casa reduziu o gasto e o valor que falta pagar no cartão. Isso não virou renda e nenhum dinheiro entrou em conta.');setAmount('');setTargetInvoiceId('');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível registrar a devolução no cartão.');}finally{setSaving(false);}};
  if(!loading&&!loadError&&initialTransactionId&&!rows.some(row=>Number(row.remaining_refundable_amount)>0&&row.eligible_invoice_targets.length>0))return null;
  return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4">
    <div className="flex items-start gap-3"><CreditCard className="mt-0.5 h-5 w-5 text-violet-300"/><div><h2 className="font-bold">Valor devolvido no cartão</h2><p className="mt-1 text-sm text-slate-400">Use quando uma compra foi devolvida ou estornada e o banco mostrou o valor como crédito em uma fatura que ainda não foi paga. O Casa reduz o gasto e o que falta pagar, sem fingir que entrou dinheiro na conta.</p></div></div>
    {loading?<LoaderCircle className="mx-auto mt-4 h-5 w-5 animate-spin text-violet-300"/>:loadError?<div className="mt-4 rounded-xl border border-rose-900 bg-rose-950/30 p-3"><p role="alert" className="text-sm text-rose-200">{loadError}</p><button type="button" onClick={()=>void load()} className="mt-3 min-h-11 rounded-xl border border-rose-800 px-3 text-sm font-semibold text-rose-200">Tentar novamente</button></div>:<form onSubmit={submit} className="mt-4 space-y-3">
      <label className="block text-sm">Qual compra teve devolução?<select value={selectedId} onChange={event=>{setSelectedId(event.target.value);setTargetInvoiceId('');setAmount('');}} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">Selecione</option>{rows.filter(row=>Number(row.remaining_refundable_amount)>0&&row.eligible_invoice_targets.length>0).map(row=><option key={row.transaction_id} value={row.transaction_id}>{row.description} · ainda pode devolver {money(row.remaining_refundable_amount)}</option>)}</select></label>
      {selected&&<div className="rounded-xl bg-slate-950 p-3 text-xs text-slate-400"><p>Valor original: <strong className="text-slate-200">{money(selected.original_amount)}</strong></p><p>Já devolvido: <strong className="text-slate-200">{money(selected.refunded_amount)}</strong></p><p>Ainda pode ser devolvido: <strong className="text-slate-200">{money(selected.remaining_refundable_amount)}</strong></p></div>}
      {selected&&<label className="block text-sm">Em qual fatura apareceu a devolução?<select value={targetInvoiceId} onChange={event=>setTargetInvoiceId(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">Selecione</option>{selected.eligible_invoice_targets.map(item=><option key={`${item.invoice_id}:${item.installment_id??'single'}`} value={item.invoice_id}>{item.installment_number?`Parcela ${item.installment_number} · `:''}fatura {item.invoice_month.slice(0,7)} · até {money(Math.min(Number(item.commitment_amount),Number(item.invoice_outstanding)))}</option>)}</select></label>}
      {target&&<p className="rounded-xl border border-violet-900/60 bg-violet-950/20 p-3 text-xs text-violet-200">O Casa vai reduzir esta fatura em até {money(Math.min(Number(target.commitment_amount),Number(target.invoice_outstanding)))}. Escolha a fatura onde o banco realmente mostrou o crédito.</p>}
      <label className="block text-sm">Quanto foi devolvido?<input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="0,00"/></label>
      <label className="block text-sm">Quando a devolução apareceu?<input type="date" value={date} onChange={event=>setDate(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label>
      <label className="block text-sm">Por que foi devolvido?<input value={reason} onChange={event=>setReason(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label>
      <p className="text-xs text-slate-500">Se o dinheiro voltou para uma conta da Casa, ou se o crédito apareceu só depois de a fatura já estar paga, use a opção específica para esse caso. Aqui tratamos somente devolução que reduz uma fatura ainda não paga.</p>
      {error&&<p role="alert" className="rounded-xl border border-rose-800 bg-rose-950/40 p-3 text-sm text-rose-200">{error}</p>}{success&&<p role="status" className="rounded-xl border border-emerald-800 bg-emerald-950/40 p-3 text-sm text-emerald-200">{success}</p>}
      <button type="submit" disabled={saving||!selected||!target} className="min-h-12 w-full rounded-xl bg-violet-600 font-bold disabled:opacity-50">{saving?'Registrando…':'Registrar devolução'}</button>
    </form>}
  </section>;
}
