import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, ChevronLeft, ChevronRight, CircleGauge, CreditCard, Landmark, LoaderCircle, PiggyBank, TrendingUp, WalletCards } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { getFinancialDashboard, getMemberFinancialPerspective, type MemberMonthlyProjection } from '../../finance/financialDashboard.js';
import { listEconomicMonthExpenses } from '../../finance/expenseMonthViews.js';
import { ensureRecurringExpenseHorizon, recurringExpenseRollingHorizonDate } from '../../finance/recurringExpenses.js';
import type { CoverageActionKind } from '../../finance/coverageActionIntent.js';
import type { SettlementActionIntent } from '../../finance/settlementActionIntent.js';
import { FinancialPriorityCenter, type AttentionNavigationAction } from './FinancialPriorityCenter.js';
import { SettlementHub } from './SettlementHub.js';
import { dateInTimeZone } from '../../finance/householdClock.js';
import { FinancialPerspectiveSelector, type FinancialPerspective } from './FinancialPerspectiveSelector.js';
import { listCardOverviews, type CardOverview } from '../../finance/cardOverview.js';
import { listHouseholdResourcePositions, listMemberResourcePositions, type HouseholdResourcePosition, type MemberResourcePosition } from '../../finance/memberResources.js';
import { UpcomingFinancialEvents } from './UpcomingFinancialEvents.js';
import { getHouseholdReferenceProjection, getMemberReferenceProjection, getReferenceMonthContext, normalizeReferenceMonth, shiftReferenceMonth, type ReferenceMonthContext } from '../../finance/referenceMonthDashboard.js';

const money=(value:number|string)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value));
const monthLabel=(value:string)=>new Intl.DateTimeFormat('pt-BR',{month:'short',year:'2-digit',timeZone:'UTC'}).format(new Date(`${value.slice(0,10)}T12:00:00Z`));
const shortDate=(value:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
const healthText={green:'Saudável',yellow:'Atenção',red:'Crítico'}as const;
const healthClass={green:'text-emerald-300',yellow:'text-amber-300',red:'text-rose-300'}as const;
const ratio=(value:number,total:number)=>total>0?Math.min(100,Math.max(0,(value/total)*100)):0;
const unavailable=(message:string)=><p role="status" className="rounded-2xl border border-amber-900/70 bg-amber-950/20 p-4 text-sm text-amber-100">{message}</p>;
type Dashboard=Awaited<ReturnType<typeof getFinancialDashboard>>;

export function CasaHomeScreen({perspective,onPerspectiveChange,onCoverageAction,onAttentionAction,onSettlementAction,onOpenInvoices,onOpenCard}:{perspective:FinancialPerspective;onPerspectiveChange:(value:FinancialPerspective)=>void;onCoverageAction?:(kind:CoverageActionKind,suggestedAmount:number)=>void;onAttentionAction?:(action:AttentionNavigationAction)=>void;onSettlementAction?:(intent:SettlementActionIntent)=>void;onOpenInvoices?:()=>void;onOpenCard?:(cardId:string)=>void}){
 const{household,householdMembers}=useSupabaseAuth();
 const[dashboard,setDashboard]=useState<Dashboard|null>(null);
 const[memberProjection,setMemberProjection]=useState<MemberMonthlyProjection[]>([]);
 const[memberCards,setMemberCards]=useState<CardOverview[]>([]);
 const[memberResources,setMemberResources]=useState<MemberResourcePosition[]>([]);
 const[householdResourceRows,setHouseholdResourceRows]=useState<HouseholdResourcePosition[]>([]);
 const[memberLoading,setMemberLoading]=useState(false);
 const[memberError,setMemberError]=useState(false);
 const[loading,setLoading]=useState(true);
 const[error,setError]=useState(false);
 const[spendInsight,setSpendInsight]=useState<{total:number;categories:Array<{name:string;amount:number}>}|null>(null);
 const[spendInsightLoading,setSpendInsightLoading]=useState(true);
 const[spendInsightError,setSpendInsightError]=useState(false);
 const[referenceMonth,setReferenceMonth]=useState('');
 const[referenceContext,setReferenceContext]=useState<ReferenceMonthContext|null>(null);
 const[referenceProjection,setReferenceProjection]=useState<Dashboard['projection']>([]);
 const[referenceMemberProjection,setReferenceMemberProjection]=useState<MemberMonthlyProjection[]>([]);
 const[referenceLoading,setReferenceLoading]=useState(false);
 const[referenceError,setReferenceError]=useState(false);
 const currentReferenceMonth=household?normalizeReferenceMonth(dateInTimeZone(household.timezone)):'';

 useEffect(()=>{if(!household)return;setReferenceMonth(normalizeReferenceMonth(dateInTimeZone(household.timezone)));},[household?.id,household?.timezone]);
 useEffect(()=>{let cancelled=false;if(!supabase||!household||!referenceMonth){setReferenceContext(null);setReferenceProjection([]);setReferenceMemberProjection([]);return()=>{cancelled=true;};}setReferenceLoading(true);setReferenceError(false);setReferenceProjection([]);setReferenceMemberProjection([]);const load=async()=>{try{const context=await getReferenceMonthContext(supabase,household.id,referenceMonth);if(cancelled)return;setReferenceContext(context);if(context.period_kind==='future'){const [householdRows,memberRows]=await Promise.all([getHouseholdReferenceProjection(supabase,household.id,referenceMonth),perspective==='household'?Promise.resolve([]):getMemberReferenceProjection(supabase,household.id,perspective,referenceMonth)]);if(cancelled)return;setReferenceProjection(householdRows);setReferenceMemberProjection(memberRows);}}catch{if(!cancelled){setReferenceContext(null);setReferenceError(true);}}finally{if(!cancelled)setReferenceLoading(false);}};void load();return()=>{cancelled=true;};},[household?.id,referenceMonth,perspective]);
 useEffect(()=>{let cancelled=false;if(!supabase||!household)return()=>{cancelled=true;};setLoading(true);setError(false);setDashboard(null);const load=async()=>{try{try{await ensureRecurringExpenseHorizon(supabase,household.id,recurringExpenseRollingHorizonDate(dateInTimeZone(household.timezone)));}catch(error){console.warn('Casa Finance: não foi possível atualizar o horizonte de despesas recorrentes antes da Home.',error);}const nextDashboard=await getFinancialDashboard(supabase,household.id,household.timezone);if(!cancelled)setDashboard(nextDashboard);}catch{if(!cancelled)setError(true);}finally{if(!cancelled)setLoading(false);}};void load();return()=>{cancelled=true;};},[household?.id,household?.timezone]);
 useEffect(()=>{let cancelled=false;if(!supabase||!household){setHouseholdResourceRows([]);return()=>{cancelled=true;};}listHouseholdResourcePositions(supabase,household.id).then(rows=>{if(!cancelled)setHouseholdResourceRows(rows);}).catch(()=>{if(!cancelled)setHouseholdResourceRows([]);});return()=>{cancelled=true;};},[household?.id]);
 useEffect(()=>{let cancelled=false;if(!supabase||!household||perspective==='household'||!referenceMonth||referenceMonth!==currentReferenceMonth){setMemberProjection([]);setMemberCards([]);setMemberResources([]);setMemberError(false);return()=>{cancelled=true;};}setMemberLoading(true);setMemberError(false);setMemberProjection([]);setMemberCards([]);setMemberResources([]);Promise.all([getMemberFinancialPerspective(supabase,household.id,perspective,household.timezone),listCardOverviews(supabase,household.id),listMemberResourcePositions(supabase,household.id,perspective)]).then(([rows,cardRows,resourceRows])=>{if(cancelled)return;setMemberProjection(rows);setMemberCards(cardRows);setMemberResources(resourceRows);}).catch(()=>{if(!cancelled)setMemberError(true);}).finally(()=>{if(!cancelled)setMemberLoading(false);});return()=>{cancelled=true;};},[household?.id,household?.timezone,perspective,referenceMonth,currentReferenceMonth]);
 useEffect(()=>{let cancelled=false;if(!supabase||!household||!referenceMonth){setSpendInsight(null);setSpendInsightLoading(false);return()=>{cancelled=true;};}setSpendInsightLoading(true);setSpendInsightError(false);const month=referenceMonth.slice(0,7);listEconomicMonthExpenses(supabase,household.id,month,perspective==='household'?undefined:perspective).then(rows=>{if(cancelled)return;const byCategory=new Map<string,number>();let total=0;for(const row of rows){const amount=Number(row.amount);total+=amount;const name=row.category?.name?.trim()||'Sem categoria';byCategory.set(name,(byCategory.get(name)??0)+amount);}const categories=[...byCategory.entries()].map(([name,amount])=>({name,amount})).sort((a,b)=>b.amount-a.amount).slice(0,3);setSpendInsight({total,categories});}).catch(()=>{if(cancelled)return;setSpendInsight(null);setSpendInsightError(true);}).finally(()=>{if(!cancelled)setSpendInsightLoading(false);});return()=>{cancelled=true;};},[household?.id,perspective,referenceMonth]);

 if(loading)return <LoaderCircle className="mx-auto mt-16 h-7 w-7 animate-spin text-blue-400"/>;
 if(error||!dashboard)return <p role="alert" className="rounded-2xl border border-rose-900 bg-rose-950/40 p-4 text-sm text-rose-200">Não foi possível carregar nenhuma fonte da posição financeira. Nenhum valor foi substituído por zero.</p>;

 const selectedMember=householdMembers.find(m=>m.id===perspective)??null;
 const{household:position,health,confidence,attention,projection,cards,resources,guidance,availability}=dashboard;
 const currentMonth=availability.projection?projection[0]:undefined;
 const currentCash=health?.current_cash!=null?Number(health.current_cash):resources?resources.availableCash:null;
 const projectedEndingCash=health?.projected_ending_cash!=null?Number(health.projected_ending_cash):position?Number(position.projected_balance):null;
 const gap=guidance?Number(guidance.coverage_gap):null;
 const hasPartialFailure=Object.values(availability).some(value=>!value);
 const selector=<FinancialPerspectiveSelector value={perspective} onChange={onPerspectiveChange}/>;
 const trackingMonth=referenceContext?.tracking_started_on?normalizeReferenceMonth(referenceContext.tracking_started_on):null;
 const previousMonth=referenceMonth?shiftReferenceMonth(referenceMonth,-1):'';
 const previousDisabled=!referenceMonth||referenceLoading||Boolean(trackingMonth&&previousMonth<trackingMonth);
 const monthNavigator=referenceMonth?<div className="flex items-center justify-between gap-2 rounded-2xl border border-slate-800 bg-slate-900/55 p-2" aria-label="Período de referência">
  <button type="button" aria-label="Mês anterior" disabled={previousDisabled} onClick={()=>setReferenceMonth(previousMonth)} className="flex h-10 w-10 items-center justify-center rounded-xl text-slate-300 disabled:cursor-not-allowed disabled:opacity-30"><ChevronLeft className="h-5 w-5"/></button>
  <button type="button" onClick={()=>setReferenceMonth(currentReferenceMonth)} className="min-h-10 flex-1 rounded-xl px-3 text-center">
   <strong className="block capitalize">{monthLabel(referenceMonth)}</strong>
   <span className="text-[10px] text-slate-500">{referenceMonth===currentReferenceMonth?'mês atual':referenceContext?.period_kind==='past'?'histórico':'planejamento'}</span>
  </button>
  <button type="button" aria-label="Próximo mês" disabled={referenceLoading} onClick={()=>setReferenceMonth(shiftReferenceMonth(referenceMonth,1))} className="flex h-10 w-10 items-center justify-center rounded-xl text-slate-300 disabled:cursor-not-allowed disabled:opacity-30"><ChevronRight className="h-5 w-5"/></button>
 </div>:null;

 if(referenceMonth&&currentReferenceMonth&&referenceMonth!==currentReferenceMonth){
  const selectedMember=householdMembers.find(m=>m.id===perspective)??null;
  const isPast=referenceContext?.period_kind==='past';
  const futureRows=perspective==='household'?referenceProjection:referenceMemberProjection;
  const futureCurrent=futureRows[0];
  const futureIncome=futureCurrent?Number(futureCurrent.realized_true_income_in_month)+Number(futureCurrent.expected_reliable_income_remaining):0;
  const futureOutflow=futureCurrent?(perspective==='household'
    ?Number((futureCurrent as Dashboard['projection'][number]).realized_commitments_in_month)+Number((futureCurrent as Dashboard['projection'][number]).remaining_commitments_in_month)+Number((futureCurrent as Dashboard['projection'][number]).projected_recurring_commitments)+Number((futureCurrent as Dashboard['projection'][number]).prior_pending_outflow)
    :Number((futureCurrent as MemberMonthlyProjection).realized_funding_in_month)+Number((futureCurrent as MemberMonthlyProjection).projected_funding_remaining)+Number((futureCurrent as MemberMonthlyProjection).scheduled_settlement_outflow)):0;
  const futureEnding=futureCurrent?(perspective==='household'?Number((futureCurrent as Dashboard['projection'][number]).projected_ending_cash):Number((futureCurrent as MemberMonthlyProjection).projected_ending_liquidity)):null;
  const openingCash=referenceContext?.historical_opening_cash==null?null:Number(referenceContext.historical_opening_cash);
  const closingCash=referenceContext?.historical_closing_cash==null?null:Number(referenceContext.historical_closing_cash);
  return <div className="space-y-7">
   <header><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">{perspective==='household'?'Nossa Casa':'Perspectiva financeira'}</p><h1 className="text-2xl font-black">{perspective==='household'?household?.name:selectedMember?.display_name??'Membro'}</h1></header>
   {monthNavigator}
   {selector}
   {referenceLoading?<LoaderCircle className="mx-auto mt-12 h-7 w-7 animate-spin text-blue-400"/>:referenceError||!referenceContext?<p role="alert" className="rounded-2xl border border-rose-900 bg-rose-950/30 p-4 text-sm text-rose-200">Não foi possível confirmar este período. O Casa não reutilizou dados do mês atual.</p>:!referenceContext.can_navigate?<p role="status" className="rounded-2xl border border-amber-900/70 bg-amber-950/20 p-4 text-sm text-amber-100">Este mês é anterior ao início do acompanhamento financeiro da Casa.</p>:isPast?<>
    <section className="rounded-[2rem] border border-slate-800 bg-gradient-to-br from-slate-900 via-slate-950 to-blue-950 p-5">
     <p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-300">Fotografia histórica</p>
     <h2 className="mt-1 text-xl font-black capitalize">{monthLabel(referenceMonth)}</h2>
     {referenceContext.coverage_state==='partial'&&<p className="mt-3 rounded-2xl bg-amber-500/10 p-3 text-xs text-amber-100">A Casa começou a ser acompanhada em {shortDate(referenceContext.tracking_started_on!)}. O período anterior a essa data não é inventado.</p>}
     {perspective==='household'?<div className="mt-5 grid grid-cols-2 gap-3"><article className="rounded-2xl bg-white/5 p-3"><p className="text-xs text-slate-400">Abertura conhecida</p><strong className="mt-1 block text-xl">{openingCash===null?'Não disponível':money(openingCash)}</strong></article><article className="rounded-2xl bg-white/5 p-3"><p className="text-xs text-slate-400">Fechamento</p><strong className="mt-1 block text-xl">{closingCash===null?'Não disponível':money(closingCash)}</strong></article></div>:<p className="mt-4 text-sm text-slate-300">O Casa mostra abaixo apenas fatos econômicos atribuídos a você neste mês. Não retrocede o saldo atual nem a titularidade atual para fabricar uma liquidez individual histórica.</p>}
     {perspective==='household'&&openingCash!==null&&closingCash!==null&&<p className="mt-4 text-sm text-slate-300">O caixa acompanhado variou <strong className={closingCash-openingCash<0?'text-rose-300':'text-emerald-300'}>{closingCash-openingCash>=0?'+ ':''}{money(closingCash-openingCash)}</strong> dentro da cobertura canônica do período.</p>}
    </section>
    <section><div className="mb-3"><h2 className="font-bold">{perspective==='household'?'O que mais pesou':'O que mais pesou pra mim'}</h2><p className="mt-1 text-xs text-slate-500">Somente gastos realizados economicamente em {monthLabel(referenceMonth)}.</p></div>{spendInsightLoading?<LoaderCircle className="h-5 w-5 animate-spin text-rose-300"/>:spendInsightError?unavailable('Não foi possível confirmar as categorias deste período.'):!spendInsight||spendInsight.total<=0?<p className="rounded-2xl border border-dashed border-slate-800 p-4 text-sm text-slate-500">Nenhum gasto realizado encontrado dentro da cobertura deste mês.</p>:<div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-4"><strong className="text-2xl text-rose-200">{money(spendInsight.total)}</strong><div className="mt-4 space-y-3">{spendInsight.categories.map(category=><div key={category.name}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate">{category.name}</span><strong>{money(category.amount)} · {Math.round(ratio(category.amount,spendInsight.total))}%</strong></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-rose-400" style={{width:String(ratio(category.amount,spendInsight.total))+'%'}}/></div></div>)}</div></div>}</section>
   </>:<>
    <section className="rounded-[2rem] border border-violet-900/60 bg-gradient-to-br from-violet-950 via-indigo-950 to-slate-900 p-5">
     <p className="text-xs font-bold uppercase tracking-[0.16em] text-violet-300">Planejamento</p><h2 className="mt-1 text-xl font-black capitalize">{monthLabel(referenceMonth)}</h2><p className="mt-2 text-xs text-white/65">Projeção baseada no que já é conhecido hoje. Não é saldo realizado nem fato futuro garantido.</p>
     {!futureCurrent?<p className="mt-5 text-sm text-slate-300">Ainda não há projeção canônica para este período.</p>:<><div className="mt-5 grid grid-cols-2 gap-3"><article className="rounded-2xl bg-white/10 p-3"><p className="text-xs text-white/70">Entradas consideradas</p><strong className="mt-1 block text-xl text-emerald-200">{money(futureIncome)}</strong></article><article className="rounded-2xl bg-white/10 p-3"><p className="text-xs text-white/70">{perspective==='household'?'Compromissos considerados':'Pode sair dos meus recursos'}</p><strong className="mt-1 block text-xl text-rose-200">{money(futureOutflow)}</strong></article></div><div className="mt-5 border-t border-white/20 pt-4"><p className="text-xs text-white/70">{perspective==='household'?'Pode terminar com':'Pode terminar comigo'}</p><strong className={'mt-1 block text-3xl '+((futureEnding??0)<0?'text-rose-300':'text-white')}>{futureEnding===null?'Não confirmado':money(futureEnding)}</strong></div></>}
    </section>
    {futureRows.length>1&&<section><h2 className="font-bold">Meses seguintes</h2><div className="-mx-4 mt-3 flex snap-x gap-3 overflow-x-auto px-4 pb-2">{futureRows.slice(1).map(row=>{const ending=perspective==='household'?Number((row as Dashboard['projection'][number]).projected_ending_cash):Number((row as MemberMonthlyProjection).projected_ending_liquidity);return <article key={row.financial_month} className="min-w-[68%] snap-start rounded-2xl bg-slate-900/60 p-4"><b className="capitalize">{monthLabel(row.financial_month)}</b><p className="mt-3 text-xs text-slate-500">Pode terminar com</p><strong className={ending<0?'text-rose-300':'text-slate-100'}>{money(ending)}</strong></article>})}</div></section>}
   </>}
  </div>;
 }

 if(perspective!=='household'){
  const current=memberProjection[0];
  const cardRows=memberCards.map(card=>({card,responsibility:card.member_responsibilities.find(item=>item.member_id===perspective)})).filter(item=>Number(item.responsibility?.member_responsibility_exposure??0)>0);
  const attributedResourceTotal=memberResources.reduce((sum,item)=>sum+Number(item.attributed_amount),0);
  const incomeTotal=current?Number(current.realized_true_income_in_month)+Number(current.expected_reliable_income_remaining):0;
  const fundingTotal=current?Number(current.realized_funding_in_month)+Number(current.projected_funding_remaining):0;
  return <div className="space-y-7"><header><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Perspectiva financeira</p><h1 className="mt-1 text-2xl font-black">{selectedMember?.display_name??'Membro'}</h1><p className="mt-1 text-xs text-slate-500">Seu retrato dentro da Casa, sem misturar comprador, responsabilidade e quem paga.</p></header>{monthNavigator}{selector}{memberLoading?<LoaderCircle className="mx-auto h-7 w-7 animate-spin"/>:memberError||!current?<p role="alert" className="rounded-2xl border border-rose-900 bg-rose-950/30 p-4 text-sm text-rose-200">Não foi possível carregar esta perspectiva financeira. Nenhum valor foi substituído por zero.</p>:<>
   <section className="rounded-[2rem] border border-blue-900/70 bg-gradient-to-br from-blue-950 via-indigo-950 to-slate-900 p-5 shadow-xl shadow-blue-950/20">
    <p className="text-xs font-bold uppercase tracking-[0.16em] text-white/70">Posso movimentar hoje</p><strong className="mt-1 block text-3xl">{money(current.opening_liquidity)}</strong><p className="mt-1 text-[11px] text-white/70">Liquidez atribuída a você agora.</p>
    <div className="mt-5 grid grid-cols-2 gap-2"><article className="rounded-2xl bg-white/10 p-3"><p className="text-[11px] text-white/70">Ainda entra</p><strong className="mt-1 block">{money(current.expected_reliable_income_remaining)}</strong></article><article className="rounded-2xl bg-white/10 p-3"><p className="text-[11px] text-white/70">Ainda pode sair</p><strong className="mt-1 block">{money(current.projected_funding_remaining)}</strong></article></div>
    <div className="mt-5 border-t border-white/20 pt-4"><p className="text-xs text-white/75">Deve sobrar comigo no fim do mês</p><strong className="mt-1 block text-2xl">{money(current.projected_ending_liquidity)}</strong><p className="mt-1 text-[11px] text-white/70">{money(incomeTotal)} de entradas consideradas · {money(fundingTotal)} de funding/pagamentos considerados.</p></div>
   </section>

   <section><div className="mb-3"><h2 className="font-bold">Minha posição</h2></div><div className="grid grid-cols-2 gap-3"><article className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-400">Minha responsabilidade</p><strong className="mt-1 block text-lg">{money(current.economic_responsibility_remaining)}</strong><span className="text-[10px] text-slate-500">O que economicamente ainda me cabe.</span></article><article className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-400">Pode sair dos meus recursos</p><strong className="mt-1 block text-lg">{money(current.projected_funding_remaining)}</strong><span className="text-[10px] text-slate-500">Pagamento/funding ainda previsto.</span></article></div></section>

   <section><div className="mb-3"><h2 className="flex items-center gap-2 text-lg font-black"><WalletCards className="h-5 w-5 text-blue-400"/>Meus recursos</h2><p className="mt-1 text-sm text-slate-400">O que está atribuído a você pelas regras de titularidade da Casa.</p></div>{memberResources.length===0?<p className="rounded-2xl bg-slate-900/35 p-4 text-sm text-slate-500">Nenhum recurso pôde ser atribuído individualmente.</p>:(()=>{const groups=[
    {key:'cash',label:'Contas e dinheiro',Icon:Landmark,tone:'text-blue-300',bg:'bg-blue-500/10',rows:memberResources.filter(item=>!item.is_investment&&item.resource_restriction!=='reserve'&&item.type!=='meal_benefit')},
    {key:'benefits',label:'Benefícios',Icon:WalletCards,tone:'text-emerald-300',bg:'bg-emerald-500/10',rows:memberResources.filter(item=>!item.is_investment&&item.type==='meal_benefit')},
    {key:'reserves',label:'Reservas',Icon:PiggyBank,tone:'text-amber-300',bg:'bg-amber-500/10',rows:memberResources.filter(item=>!item.is_investment&&item.resource_restriction==='reserve')},
    {key:'investments',label:'Investimentos',Icon:TrendingUp,tone:'text-violet-300',bg:'bg-violet-500/10',rows:memberResources.filter(item=>item.is_investment)}
   ];return <div className="space-y-2"><div className="mb-2 px-1"><p className="text-sm text-slate-500">Recursos atribuídos</p><strong className="text-3xl">{money(attributedResourceTotal)}</strong></div>{groups.map(group=>{const total=group.rows.reduce((sum,item)=>sum+Number(item.attributed_amount),0);return <details key={group.key} className="group overflow-hidden rounded-2xl bg-slate-900/55"><summary className="flex min-h-16 cursor-pointer list-none items-center gap-3 px-4 py-3"><span className={`flex h-10 w-10 items-center justify-center rounded-2xl ${group.bg} ${group.tone}`}><group.Icon className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="font-bold text-slate-200">{group.label}</p><p className="text-xs text-slate-500">{group.rows.length>0?`${group.rows.length} ${group.rows.length===1?'item':'itens'}`:'Nenhum item'}</p></div><strong className="text-lg">{money(total)}</strong><ChevronRight className="h-4 w-4 text-slate-600 transition-transform group-open:rotate-90"/></summary>{group.rows.length>0&&<div className="border-t border-slate-800/70 px-3 py-2">{group.rows.map(item=><div key={item.account_id} className="flex items-center justify-between gap-3 rounded-xl px-2 py-2.5"><div className="min-w-0"><p className="truncate text-sm text-slate-300">{item.name}</p>{item.allocation_ratio<1&&<p className="text-xs text-slate-500">Sua parte {Math.round(item.allocation_ratio*100)}%</p>}</div><strong className="text-sm">{money(item.attributed_amount)}</strong></div>)}</div>}</details>})}</div>})()}</section>

   <section><div className="mb-3"><h2 className="flex items-center gap-2 text-lg font-black"><CreditCard className="h-5 w-5 text-violet-400"/>Meus cartões</h2><p className="mt-1 text-sm text-slate-400">Sua responsabilidade dentro dos cartões da Casa.</p></div>{cardRows.length===0?<p className="rounded-2xl bg-slate-900/35 p-4 text-sm text-slate-500">Nenhum compromisso seu em cartões agora.</p>:<div className="space-y-2">{cardRows.map(({card,responsibility})=><article key={card.card_id} role="button" tabIndex={0} onClick={()=>onOpenCard?.(card.card_id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onOpenCard?.(card.card_id)}}} className="cursor-pointer rounded-[1.5rem] bg-slate-900/60 p-4 transition-transform hover:-translate-y-0.5"><div className="flex items-start justify-between gap-3"><div><b className="text-base">{card.card_name}</b><p className="mt-1 text-xs text-slate-500">{card.next_due_date?'Vence '+shortDate(card.next_due_date):'Sem vencimento confirmado'}</p></div><ChevronRight className="h-5 w-5 text-slate-600"/></div><div className="mt-4 grid grid-cols-3 gap-2"><div><p className="text-xs text-slate-500">Minha fatura</p><strong className="mt-1 block text-base">{money(responsibility?.member_current_invoice_responsibility??0)}</strong></div><div><p className="text-xs text-slate-500">Meu futuro</p><strong className="mt-1 block text-base">{money(responsibility?.member_future_responsibility??0)}</strong></div><div><p className="text-xs text-slate-500">Limite livre</p><strong className="mt-1 block text-base text-emerald-300">{money(card.available_limit)}</strong></div></div><p className="mt-3 text-xs text-slate-500">O limite continua sendo do cartão; os valores acima mostram apenas sua responsabilidade econômica.</p></article>)}<button type="button" onClick={onOpenInvoices} className="mt-1 flex min-h-11 w-full items-center justify-center gap-1 text-sm font-bold text-violet-300">Todas as faturas<ChevronRight className="h-4 w-4"/></button></div>}</section>

   <UpcomingFinancialEvents perspective={perspective} onOpenCard={onOpenCard}/>

   <section><div className="mb-3"><h2 className="font-bold">O que mais pesou pra mim</h2><p className="mt-1 text-xs text-slate-500">Principais categorias pela sua responsabilidade econômica realizada.</p></div>{spendInsightLoading?<LoaderCircle className="h-5 w-5 animate-spin text-rose-300"/>:spendInsightError?unavailable('Não foi possível confirmar suas categorias agora.'):!spendInsight||spendInsight.total<=0?<p className="text-sm text-slate-500">Ainda não há gastos seus para resumir neste mês.</p>:<div className="space-y-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4">{spendInsight.categories.map(category=><div key={category.name}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate">{category.name}</span><strong>{money(category.amount)} · {Math.round(ratio(category.amount,spendInsight.total))}%</strong></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-rose-400" style={{width:String(ratio(category.amount,spendInsight.total))+'%'}}/></div></div>)}</div>}</section>

   <section><div className="mb-3"><h2 className="font-bold">Acerto entre nós</h2></div><div className="grid grid-cols-2 gap-3"><article className="rounded-2xl border border-emerald-900/50 bg-emerald-950/20 p-4"><p className="text-xs text-emerald-300">Tenho a receber</p><strong className="mt-1 block text-lg">{money(current.settlement_receivable_position)}</strong></article><article className="rounded-2xl border border-amber-900/50 bg-amber-950/20 p-4"><p className="text-xs text-amber-300">Preciso acertar</p><strong className="mt-1 block text-lg">{money(current.settlement_payable_position)}</strong></article></div></section>

   <section><h2 className="text-lg font-black">Olhando pra frente</h2><p className="mt-1 text-sm text-slate-400">Como sua liquidez pode evoluir nos próximos meses.</p>{memberProjection.length===0?<p className="mt-3 text-sm text-slate-500">Ainda não há projeções individuais.</p>:<div className="-mx-4 mt-3 flex snap-x gap-3 overflow-x-auto px-4 pb-2">{memberProjection.map((m,index)=><article key={m.financial_month} className="min-w-[76%] snap-start rounded-[1.5rem] bg-slate-900/60 p-4 sm:min-w-[46%]"><div className="flex items-center justify-between"><b className="capitalize">{monthLabel(m.financial_month)}</b>{index===0&&<span className="rounded-full bg-blue-500/10 px-2 py-1 text-[11px] font-bold text-blue-300">agora</span>}</div><p className="mt-4 text-xs text-slate-500">Pode terminar comigo</p><strong className={`mt-1 block text-2xl ${Number(m.projected_ending_liquidity)<0?'text-rose-300':'text-slate-100'}`}>{money(m.projected_ending_liquidity)}</strong>{m.projected_net_change!==0&&<p className={`mt-1 text-xs font-semibold ${m.projected_net_change<0?'text-rose-300':'text-emerald-300'}`}>{m.projected_net_change>0?'▲ ':'▼ '}{money(Math.abs(m.projected_net_change))} no mês</p>}<div className="mt-4 flex justify-between gap-3 text-xs"><span className="text-emerald-300">+ {money(Number(m.realized_true_income_in_month)+Number(m.expected_reliable_income_remaining)+Number(m.scheduled_settlement_inflow))}</span><span className="text-rose-300">− {money(Number(m.realized_funding_in_month)+Number(m.projected_funding_remaining)+Number(m.scheduled_settlement_outflow))}</span></div></article>)}</div>}</section>
  </>}</div>;
 }

 return <div className="space-y-7">
  <header><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Nossa Casa</p><h1 className="text-2xl font-black">{household?.name}</h1></header>
  {monthNavigator}
  {selector}
  {hasPartialFailure&&<p role="status" className="rounded-2xl border border-amber-900/70 bg-amber-950/20 p-4 text-sm text-amber-100">Algumas análises não puderam ser confirmadas agora. O Casa mantém visíveis apenas os dados que conseguiu ler e não substitui informações ausentes por R$ 0,00.</p>}

  <section>
   <h2 className="mb-3 flex items-center gap-2 font-bold"><CircleGauge className="h-5 w-5 text-blue-400"/>Como estamos?</h2>
   <div className="rounded-[2rem] border border-blue-900/70 bg-gradient-to-br from-blue-950 via-indigo-950 to-slate-900 p-5 shadow-xl shadow-blue-950/20">
    <div className="flex items-start justify-between gap-3">
     <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-white/70">Agora</p>{currentCash===null?<strong className="mt-1 block text-xl">Não confirmado</strong>:<strong className="mt-1 block text-3xl">{money(currentCash)}</strong>}<p className="mt-1 text-xs text-white/70">Saldo atual em contas e dinheiro físico.</p></div>
     <div className="flex flex-col items-end gap-2">{health&&<span className={`rounded-full bg-white/8 px-2.5 py-1 text-xs font-bold ${healthClass[health.health]}`}>{healthText[health.health]}</span>}{confidence&&confidence.confidence_state!=='well_updated'&&<span className="max-w-44 rounded-full bg-amber-400/10 px-2.5 py-1 text-right text-[11px] font-semibold text-amber-200">{confidence.confidence_label}</span>}</div>
    </div>
    {position&&<div className="mt-5 grid grid-cols-2 gap-2">
     <article className="rounded-2xl bg-white/10 p-3"><p className="text-[11px] text-white/70">Já tem destino</p><strong className="mt-1 block text-lg">{money(position.committed_balance)}</strong><p className="mt-1 text-[10px] text-white/60">Faturas e compromissos conhecidos.</p></article>
     <article className="rounded-2xl bg-white/10 p-3"><p className="text-[11px] text-white/70">Livre depois deles</p><strong className="mt-1 block text-lg">{money(position.projected_balance)}</strong><p className="mt-1 text-[10px] text-white/60">Antes de novas entradas.</p></article>
    </div>}
    {position&&currentCash!==null&&currentCash>0&&<div className="mt-4"><div className="mb-1 flex justify-between text-[11px] text-white/70"><span>Quanto do dinheiro de agora já tem destino</span><span>{Math.round(ratio(Number(position.committed_balance),currentCash))}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-white/80" style={{width:`${ratio(Number(position.committed_balance),currentCash)}%`}}/></div></div>}
    <div className="mt-5 border-t border-white/20 pt-4"><p className="text-xs text-white/75">Deve sobrar no fim do mês</p>{projectedEndingCash===null?<strong className="mt-1 block text-lg">Não confirmado</strong>:<strong className="mt-1 block text-2xl">{money(projectedEndingCash)}</strong>}<p className="mt-1 text-[11px] text-white/65">Considera somente entradas confiáveis ainda esperadas e compromissos conhecidos.</p></div>
    {currentCash!==null&&position&&projectedEndingCash!==null&&<p className="mt-4 rounded-2xl bg-slate-950/20 p-3 text-xs leading-5 text-white/85">Temos <strong>{money(currentCash)}</strong> agora. <strong>{money(position.committed_balance)}</strong> já têm destino. Com o que ainda está previsto entrar e sair, o mês tende a terminar em <strong>{money(projectedEndingCash)}</strong>.</p>}
   </div>
   {!availability.guidance&&unavailable('A orientação de cobertura está indisponível agora. O Casa não vai presumir quanto está livre ou faltando.')}
   {guidance&&guidance.guidance_state!=='covered'&&<article className="mt-3 rounded-2xl border border-rose-900/70 bg-rose-950/20 p-4"><h3 className="font-bold">{guidance.guidance_title}</h3>{guidance.guidance_state==='covered_by_expected_income'?<p className="mt-1 text-sm">O caixa atual sozinho não cobre tudo, mas as entradas confiáveis previstas fecham o mês. O Casa continuará acompanhando se elas realmente entrarem.</p>:<><p className="mt-1 text-sm">Faltam <strong>{money(gap??0)}</strong> na projeção para cobrir os compromissos conhecidos.</p><p className="mt-2 text-xs text-slate-400">Escolha uma opção somente se ela realmente acontecer. Abrir uma opção abaixo não movimenta dinheiro nem muda a projeção.</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><button onClick={()=>onCoverageAction?.('transfer',gap??0)} className="min-h-11 rounded-xl border border-slate-700 px-3 text-sm font-bold">Mover dinheiro de outra conta da Casa</button>{Number(guidance.reserve_balance)+Number(guidance.investment_balance)>0&&<button onClick={()=>onCoverageAction?.('reserve',gap??0)} className="min-h-11 rounded-xl border border-slate-700 px-3 text-sm font-bold">Usar dinheiro de uma reserva ou investimento</button>}<button onClick={()=>onCoverageAction?.('loan',gap??0)} className="min-h-11 rounded-xl border border-slate-700 px-3 text-sm font-bold">Pegar dinheiro emprestado</button></div><p className="mt-2 text-xs text-slate-500">O Casa nunca usa outra conta, reserva, investimento ou crédito automaticamente. Você escolhe e confirma cada movimento.</p></>}</article>}
  </section>

  {availability.attention?<FinancialPriorityCenter items={attention} onNavigate={onAttentionAction}/>:unavailable('Não foi possível conferir o centro de atenção. Nenhuma pendência foi presumida como resolvida.')}

  <section>
   <div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="flex items-center gap-2 font-bold"><TrendingUp className="h-5 w-5 text-emerald-400"/>Fluxo deste mês</h2><p className="mt-1 text-xs text-slate-500">Recebido, esperado, realizado e ainda pela frente — sem misturar previsão com dinheiro que já entrou ou saiu.</p></div>{currentMonth&&<span className="rounded-full border border-slate-800 bg-slate-900 px-3 py-1 text-xs font-bold text-slate-300">{monthLabel(currentMonth.financial_month)}</span>}</div>
   {!availability.projection?unavailable('Não foi possível confirmar a projeção deste mês.'):!currentMonth?<p className="text-sm text-slate-400">Ainda não há projeção financeira para este mês.</p>:(()=>{const entered=Number(currentMonth.realized_true_income_in_month);const expected=Number(currentMonth.expected_reliable_income_remaining);const paid=Number(currentMonth.realized_commitments_in_month);const pending=Number(currentMonth.remaining_commitments_in_month)+Number(currentMonth.projected_recurring_commitments)+Number(currentMonth.prior_pending_outflow);const incomeTotal=entered+expected;const commitmentTotal=paid+pending;return <div className="space-y-3">
    <article className="rounded-3xl border border-emerald-900/40 bg-emerald-950/15 p-4">
     <div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-1 text-xs font-bold text-emerald-300"><ArrowUpRight className="h-4 w-4"/>Entradas</p><strong className="mt-1 block text-xl">{money(incomeTotal)}</strong></div><p className="text-right text-[11px] text-slate-400"><strong className="text-slate-200">{money(entered)}</strong> já entrou<br/>{money(expected)} ainda esperado</p></div>
     {incomeTotal>0&&<div className="mt-3"><div className="mb-1 flex justify-between text-[10px] text-slate-500"><span>Quanto das entradas consideradas já chegou</span><span>{Math.round(ratio(entered,incomeTotal))}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-400" style={{width:`${ratio(entered,incomeTotal)}%`}}/></div></div>}
    </article>
    <article className="rounded-3xl border border-rose-900/40 bg-rose-950/10 p-4">
     <div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-1 text-xs font-bold text-rose-300"><ArrowDownRight className="h-4 w-4"/>Compromissos</p><strong className="mt-1 block text-xl">{money(commitmentTotal)}</strong></div><p className="text-right text-[11px] text-slate-400"><strong className="text-slate-200">{money(paid)}</strong> já realizado/pago<br/>{money(pending)} ainda pela frente</p></div>
     {commitmentTotal>0&&<div className="mt-3"><div className="mb-1 flex justify-between text-[10px] text-slate-500"><span>Quanto dos compromissos considerados já aconteceu</span><span>{Math.round(ratio(paid,commitmentTotal))}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-rose-400" style={{width:`${ratio(paid,commitmentTotal)}%`}}/></div></div>}
    </article>
   </div>})()}
  </section>

  <section>
   <div className="mb-3"><h2 className="flex items-center gap-2 text-lg font-black"><WalletCards className="h-5 w-5 text-blue-400"/>Onde está nosso dinheiro</h2><p className="mt-1 text-sm text-slate-400">Um retrato dos recursos da Casa. Toque em cada grupo para ver o que compõe o valor.</p></div>
   {!availability.resources||!resources?unavailable('Não foi possível confirmar os saldos dos recursos da Casa.'):(()=>{const groups=[
    {key:'cash',label:'Contas e dinheiro',value:resources.availableCash,Icon:Landmark,tone:'text-blue-300',bg:'bg-blue-500/10',rows:householdResourceRows.filter(item=>!item.is_investment&&item.resource_restriction!=='reserve'&&item.type!=='meal_benefit')},
    {key:'benefits',label:'Benefícios',value:resources.benefits,Icon:WalletCards,tone:'text-emerald-300',bg:'bg-emerald-500/10',rows:householdResourceRows.filter(item=>!item.is_investment&&item.type==='meal_benefit')},
    {key:'reserves',label:'Reservas',value:resources.reserves,Icon:PiggyBank,tone:'text-amber-300',bg:'bg-amber-500/10',rows:householdResourceRows.filter(item=>!item.is_investment&&item.resource_restriction==='reserve')},
    {key:'investments',label:'Investimentos',value:resources.investments,Icon:TrendingUp,tone:'text-violet-300',bg:'bg-violet-500/10',rows:householdResourceRows.filter(item=>item.is_investment)}
   ];const resourceTotal=groups.reduce((sum,group)=>sum+group.value,0);return <div className="space-y-2"><div className="mb-2 flex items-end justify-between gap-3 px-1"><div><p className="text-sm text-slate-400">Patrimônio financeiro acompanhado</p><strong className="text-3xl">{money(resourceTotal)}</strong></div><span className="text-xs text-slate-500">{householdResourceRows.length} {householdResourceRows.length===1?'recurso':'recursos'}</span></div>{groups.map(group=><details key={group.key} className="group overflow-hidden rounded-2xl bg-slate-900/55"><summary className="flex min-h-16 cursor-pointer list-none items-center gap-3 px-4 py-3"><span className={`flex h-10 w-10 items-center justify-center rounded-2xl ${group.bg} ${group.tone}`}><group.Icon className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="font-bold text-slate-200">{group.label}</p><p className="text-xs text-slate-500">{group.rows.length>0?`${group.rows.length} ${group.rows.length===1?'item':'itens'}`:'Nenhum item cadastrado'}</p></div><strong className="text-lg">{money(group.value)}</strong><ChevronRight className="h-4 w-4 text-slate-600 transition-transform group-open:rotate-90"/></summary>{group.rows.length>0&&<div className="border-t border-slate-800/70 px-3 py-2">{group.rows.map(item=><div key={item.account_id} className="flex items-center justify-between gap-3 rounded-xl px-2 py-2.5"><p className="truncate text-sm text-slate-300">{item.name}</p><strong className="text-sm">{money(item.current_balance)}</strong></div>)}</div>}</details>)}</div>})()}
  </section>

  <section>
   <div className="mb-3"><h2 className="flex items-center gap-2 text-lg font-black"><CreditCard className="h-5 w-5 text-violet-400"/>Cartões</h2><p className="mt-1 text-sm text-slate-400">Fatura, limite e compromissos futuros. Toque no cartão para abrir o detalhe.</p></div>
   {!availability.cards?unavailable('Não foi possível confirmar faturas e exposição dos cartões agora.'):cards.length===0?<p className="text-sm text-slate-400">Nenhum cartão acompanhado pela Casa.</p>:<div className="space-y-2">{cards.map(c=>{const usage=c.utilization_ratio==null?null:Number(c.utilization_ratio)*100;const healthLabel=c.card_health==='red'?'Crítico':c.card_health==='yellow'?'Atenção':'Confortável';const healthTone=c.card_health==='red'?'text-rose-300':c.card_health==='yellow'?'text-amber-300':'text-emerald-300';return <article key={c.card_id} role="button" tabIndex={0} onClick={()=>onOpenCard?.(c.card_id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onOpenCard?.(c.card_id)}}} className="cursor-pointer rounded-[1.6rem] bg-slate-900/60 p-4 transition-transform hover:-translate-y-0.5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><b className="text-base">{c.card_name}</b><span className={'text-xs font-bold '+healthTone}>{healthLabel}</span></div><p className="mt-1 text-xs text-slate-500">{c.next_due_date?'Vence '+shortDate(c.next_due_date):'Sem vencimento confirmado'}</p></div><ChevronRight className="h-5 w-5 text-slate-600"/></div><div className="mt-4 grid grid-cols-3 gap-2"><div><p className="text-xs text-slate-500">Fatura</p><strong className="mt-1 block text-base">{money(c.current_invoice_remaining)}</strong></div><div><p className="text-xs text-slate-500">Futuro</p><strong className="mt-1 block text-base">{money(c.future_known_commitments)}</strong></div><div><p className="text-xs text-slate-500">Limite livre</p><strong className={'mt-1 block text-base '+(c.available_limit<0?'text-rose-300':'text-emerald-300')}>{money(c.available_limit)}</strong></div></div>{usage!=null&&<div className="mt-4"><div className="mb-1 flex justify-between text-xs text-slate-500"><span>Crédito comprometido</span><span>{Math.round(usage)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className={'h-full rounded-full '+(c.card_health==='red'?'bg-rose-400':c.card_health==='yellow'?'bg-amber-400':'bg-violet-400')} style={{width:String(Math.min(100,Math.max(0,usage)))+'%'}}/></div></div>}{c.over_limit_amount>0&&<p className="mt-2 text-xs font-semibold text-rose-300">Acima do limite em {money(c.over_limit_amount)}.</p>}</article>})}<button type="button" onClick={onOpenInvoices} className="mt-1 flex min-h-11 w-full items-center justify-center gap-1 text-sm font-bold text-violet-300">Todas as faturas<ChevronRight className="h-4 w-4"/></button></div>}
  </section>

  <UpcomingFinancialEvents perspective={perspective} onOpenCard={onOpenCard}/>

  <section>
   <div className="mb-3"><h2 className="font-bold">O que mais pesou</h2><p className="mt-1 text-xs text-slate-500">As maiores categorias dos gastos que realmente aconteceram neste mês.</p></div>
   {spendInsightLoading?<div className="flex min-h-20 items-center justify-center rounded-2xl border border-slate-800 bg-slate-900/40"><LoaderCircle className="h-5 w-5 animate-spin text-rose-300"/></div>:spendInsightError?unavailable('Não foi possível confirmar a leitura por categoria agora.'):!spendInsight||spendInsight.total<=0?<p className="rounded-2xl border border-dashed border-slate-800 p-4 text-sm text-slate-500">Ainda não há gastos realizados para resumir neste mês.</p>:<div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex items-end justify-between gap-3"><div><p className="text-[11px] uppercase tracking-wide text-slate-500">Gasto realizado</p><strong className="mt-1 block text-2xl text-rose-200">{money(spendInsight.total)}</strong></div><span className="text-[10px] text-slate-500">top 3 categorias</span></div><div className="mt-4 space-y-3">{spendInsight.categories.map(category=><div key={category.name}><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="truncate text-slate-300">{category.name}</span><span className="shrink-0 font-semibold">{money(category.amount)} · {Math.round(ratio(category.amount,spendInsight.total))}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-rose-400" style={{width:`${ratio(category.amount,spendInsight.total)}%`}}/></div></div>)}</div><p className="mt-4 text-[10px] leading-4 text-slate-500">Mostra onde o gasto econômico aconteceu. Compra parcelada entra uma vez pelo valor da compra; pagamento de fatura não vira outro gasto. Isso não é uma meta de orçamento.</p></div>}
  </section>

  <SettlementHub onResolve={onSettlementAction}/>

  <section>
   <div className="mb-3"><h2 className="flex items-center gap-2 text-lg font-black"><Landmark className="h-5 w-5 text-emerald-400"/>Olhando pra frente</h2><p className="mt-1 text-sm text-slate-400">Uma leitura rápida de como o caixa pode fechar nos próximos meses.</p></div>
   {!availability.projection?unavailable('Não foi possível confirmar a projeção dos próximos meses.'):projection.length===0?<p className="text-sm text-slate-400">Ainda não há projeções futuras.</p>:(()=>{const maxEnding=Math.max(1,...projection.map(month=>Math.abs(Number(month.projected_ending_cash))));return <div className="-mx-4 flex snap-x gap-3 overflow-x-auto px-4 pb-2">{projection.map((m,index)=>{const income=Number(m.realized_true_income_in_month)+Number(m.expected_reliable_income_remaining);const commitments=Number(m.realized_commitments_in_month)+Number(m.remaining_commitments_in_month)+Number(m.projected_recurring_commitments)+Number(m.prior_pending_outflow);const ending=Number(m.projected_ending_cash);const previousEnding=index>0?Number(projection[index-1].projected_ending_cash):null;const delta=previousEnding===null?null:ending-previousEnding;return <article key={m.financial_month} className="min-w-[78%] snap-start rounded-[1.6rem] bg-slate-900/60 p-4 sm:min-w-[48%]"><div className="flex items-center justify-between gap-2"><b className="capitalize">{monthLabel(m.financial_month)}</b>{index===0&&<span className="rounded-full bg-blue-500/10 px-2 py-1 text-[11px] font-bold text-blue-300">agora</span>}</div><p className="mt-4 text-xs text-slate-500">Pode terminar com</p><strong className={`mt-1 block text-2xl ${ending<0?'text-rose-300':'text-slate-100'}`}>{money(ending)}</strong>{delta!==null&&<p className={`mt-1 text-xs font-semibold ${delta<0?'text-rose-300':delta>0?'text-emerald-300':'text-slate-500'}`}>{delta>0?'▲ ':delta<0?'▼ ':''}{money(Math.abs(delta))} vs. mês anterior</p>}<div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${ending<0?'bg-rose-400':'bg-emerald-400'}`} style={{width:String(Math.max(8,Math.min(100,Math.abs(ending)/maxEnding*100)))+'%'}}/></div><div className="mt-4 flex justify-between gap-3 text-xs"><span className="text-emerald-300">+ {money(income)}</span><span className="text-rose-300">− {money(commitments)}</span></div></article>})}</div>})()}
  </section>
 </div>;
}
