import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { RefreshCcw, LoaderCircle } from 'lucide-react';
import { supabase } from '../../lib/supabase.js';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { correctExpenseRoles, listExpenseRoleCorrectionPositions, type ExpenseRoleCorrectionPosition } from '../../finance/expenseRoleCorrections.js';

const money=(value:number|string|null|undefined)=>Number(value??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export function ExpenseRoleCorrectionAction({initialTransactionId,compact=false}:{initialTransactionId?:string;compact?:boolean}={}){
  const{household,householdMembers}=useSupabaseAuth();
  const[rows,setRows]=useState<ExpenseRoleCorrectionPosition[]>([]);const[selectedId,setSelectedId]=useState('');const[buyer,setBuyer]=useState('');const[firstMember,setFirstMember]=useState('');const[firstPct,setFirstPct]=useState('100');const[secondMember,setSecondMember]=useState('');const[reason,setReason]=useState('Correção de comprador/responsabilidade');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[loadError,setLoadError]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[success,setSuccess]=useState<string|null>(null);
  const clearLoadedContext=()=>{setRows([]);setSelectedId('');setBuyer('');setFirstMember('');setFirstPct('100');setSecondMember('');};
  const load=async()=>{if(!supabase||!household)return;setLoading(true);setLoadError(null);setError(null);try{const nextRows=await listExpenseRoleCorrectionPositions(supabase,household.id);setRows(initialTransactionId?nextRows.filter(row=>row.transaction_id===initialTransactionId):nextRows);}catch{clearLoadedContext();setLoadError('Não foi possível conferir os gastos elegíveis para correção. Nenhum comprador ou responsabilidade será alterado até uma nova leitura válida.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[household?.id]);
  const selected=useMemo(()=>rows.find(row=>row.transaction_id===selectedId)??null,[rows,selectedId]);
  useEffect(()=>{if(initialTransactionId&&rows.some(row=>row.transaction_id===initialTransactionId))setSelectedId(initialTransactionId);},[initialTransactionId,rows]);
  useEffect(()=>{if(!selected)return;setBuyer(selected.buyer_member_id??'');const resp=selected.responsibility??[];setFirstMember(resp[0]?.member_id??'');setFirstPct(String(Number(resp[0]?.percentage??100)));setSecondMember(resp[1]?.member_id??'');},[selectedId]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(loadError||loading){setError('Recarregue os gastos elegíveis antes de corrigir comprador ou responsabilidade.');return;}if(!supabase||!household||!selected)return;const pct=Number(firstPct);const effectiveBuyer=compact?(selected.buyer_member_id??''):buyer;if((!effectiveBuyer)||!firstMember||!Number.isFinite(pct)||pct<=0||pct>100||!reason.trim()){setError('Revise comprador, responsabilidade, percentual e motivo.');return;}if(pct<100&&(!secondMember||secondMember===firstMember)){setError('Escolha uma segunda pessoa diferente para completar o rateio.');return;}const responsibility=pct===100?[{member_id:firstMember,percentage:100}]:[{member_id:firstMember,percentage:pct},{member_id:secondMember,percentage:100-pct}];setSaving(true);setError(null);setSuccess(null);try{await correctExpenseRoles(supabase,{householdId:household.id,transactionId:selected.transaction_id,buyerMemberId:effectiveBuyer,responsibility,reason});setSuccess('Correção registrada com histórico. Funding e caixa anteriores foram preservados; apenas responsabilidade e acertos derivados foram recalculados.');setSelectedId('');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível corrigir os papéis do gasto.');}finally{setSaving(false);}};
  if(!loading&&!loadError&&initialTransactionId&&rows.length===0)return null;
  return <section className={compact?'rounded-2xl border border-cyan-900/50 bg-cyan-950/10 p-3':'rounded-2xl border border-slate-800 bg-slate-900 p-4'}>
    <div className="flex items-start gap-3"><RefreshCcw className="mt-0.5 h-5 w-5 text-cyan-300"/><div><h2 className="font-bold">Responsabilidade do gasto</h2><p className="mt-1 text-sm text-slate-400">Ajuste quem assume este gasto. Isso não muda quem realmente pagou nem reescreve o caixa do passado.</p></div></div>
    {loading?<LoaderCircle className="mx-auto mt-4 h-5 w-5 animate-spin text-cyan-300"/>:loadError?<div className="mt-4 rounded-xl border border-rose-900 bg-rose-950/30 p-3"><p role="alert" className="text-sm text-rose-200">{loadError}</p><button type="button" onClick={()=>void load()} className="mt-3 min-h-11 rounded-xl border border-rose-800 px-3 text-sm font-semibold text-rose-200">Tentar novamente</button></div>:<form onSubmit={submit} className="mt-4 space-y-3">
      <label className={compact?"sr-only":"block text-sm"}>Qual gasto precisa ser corrigido?<select value={selectedId} onChange={event=>setSelectedId(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">Selecione</option>{rows.map(row=><option key={row.transaction_id} value={row.transaction_id}>{row.description} · {row.transaction_date}</option>)}</select></label>
      {selected&&<div className="rounded-xl bg-slate-950 p-3 text-xs text-slate-400"><p>{selected.has_funding||selected.has_cash_effect?'Este gasto já tem efeitos financeiros.':'Este gasto ainda não tem funding/caixa realizado.'}</p><p>Responsabilidade atual: {selected.responsibility.map(item=>`${householdMembers.find(member=>member.id===item.member_id)?.display_name??'Membro'} ${Number(item.percentage)}% (${money(item.amount)})`).join(' · ')}</p>{!compact&&<p>Correções anteriores: {selected.correction_count}</p>}</div>}
      {selected&&<>{!compact&&<label className="block text-sm">Quem realmente comprou?<select value={buyer} onChange={event=>setBuyer(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">Selecione</option>{householdMembers.map(member=><option key={member.id} value={member.id}>{member.display_name}</option>)}</select></label>}<label className="block text-sm">Quem assume o gasto?<select value={firstMember} onChange={event=>setFirstMember(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">Selecione</option>{householdMembers.map(member=><option key={member.id} value={member.id}>{member.display_name}</option>)}</select></label><label className="block text-sm">Percentual desta pessoa<input inputMode="decimal" value={firstPct} onChange={event=>setFirstPct(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label>{Number(firstPct)<100&&<label className="block text-sm">Quem assume o restante ({Math.max(100-Number(firstPct||0),0)}%)?<select value={secondMember} onChange={event=>setSecondMember(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">Selecione</option>{householdMembers.map(member=><option key={member.id} value={member.id}>{member.display_name}</option>)}</select></label>}<label className="block text-sm">Motivo da correção<input value={reason} onChange={event=>setReason(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><p className="text-xs text-slate-500">Comprador, responsável econômico e financiador continuam independentes. Se já houve pagamento, o funding histórico não muda; o Casa apenas recalcula os acertos que dependem da responsabilidade correta.</p></>}
      {error&&<p role="alert" className="rounded-xl border border-rose-800 bg-rose-950/40 p-3 text-sm text-rose-200">{error}</p>}{success&&<p role="status" className="rounded-xl border border-emerald-800 bg-emerald-950/40 p-3 text-sm text-emerald-200">{success}</p>}
      <button type="submit" disabled={saving||!selected} className="min-h-12 w-full rounded-xl bg-cyan-700 font-bold disabled:opacity-50">{saving?'Corrigindo…':'Registrar correção auditável'}</button>
    </form>}
  </section>;
}
