import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, LoaderCircle, ReceiptText } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { listEconomicMonthExpenses, listFinancialMonthExpenses, type EconomicMonthExpense, type FinancialMonthExpense } from '../../finance/expenseMonthViews.js';

const money=(value:number|string|null|undefined)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value??0));
const currentMonth=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit'}).formatToParts(new Date());const year=parts.find(part=>part.type==='year')?.value??'';const month=parts.find(part=>part.type==='month')?.value??'';return `${year}-${month}`;};
const monthName=(value:string)=>new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}-01T12:00:00Z`));
const sourceLabel=(row:FinancialMonthExpense)=>row.source_type==='card_installment'?'Parcela do cartão':row.source_type==='recurring_occurrence'?'Gasto recorrente':'Gasto do mês';
const stateLabel=(state:string)=>state==='realized'?'Pago/realizado':state==='confirmed'?'Confirmado':'';
const percentage=(value:number,total:number)=>total>0?Math.max(0,(value/total)*100):0;
const barWidth=(value:number,total:number)=>Math.min(100,percentage(value,total));

type ViewMode='financial'|'economic';
type CategorySummary={name:string;amount:number};

export function ExpenseMonthBrowser({refreshKey=0}:{refreshKey?:number}){
  const{household}=useSupabaseAuth();
  const[month,setMonth]=useState(currentMonth());
  const[mode,setMode]=useState<ViewMode>('financial');
  const[financialRows,setFinancialRows]=useState<FinancialMonthExpense[]>([]);
  const[economicRows,setEconomicRows]=useState<EconomicMonthExpense[]>([]);
  const[loading,setLoading]=useState(true);
  const[error,setError]=useState(false);
  const[refreshVersion,setRefreshVersion]=useState(0);

  useEffect(()=>{let cancelled=false;if(!supabase||!household){setLoading(false);return()=>{cancelled=true;};}setLoading(true);setError(false);setFinancialRows([]);setEconomicRows([]);const request=mode==='financial'?listFinancialMonthExpenses(supabase,household.id,month):listEconomicMonthExpenses(supabase,household.id,month);request.then(rows=>{if(cancelled)return;if(mode==='financial')setFinancialRows(rows as FinancialMonthExpense[]);else setEconomicRows(rows as EconomicMonthExpense[]);}).catch(()=>{if(cancelled)return;setFinancialRows([]);setEconomicRows([]);setError(true);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[household?.id,month,mode,refreshKey,refreshVersion]);

  const financialSummary=useMemo(()=>financialRows.reduce((summary,row)=>({total:summary.total+Number(row.effective_amount),realized:summary.realized+Number(row.realized_amount),remaining:summary.remaining+Number(row.remaining_amount)}),{total:0,realized:0,remaining:0}),[financialRows]);
  const economicSummary=useMemo(()=>{const byCategory=new Map<string,number>();let total=0;for(const row of economicRows){const amount=Number(row.amount);total+=amount;const name=row.category?.name?.trim()||'Sem categoria';byCategory.set(name,(byCategory.get(name)??0)+amount);}const categories=[...byCategory.entries()].map(([name,amount])=>({name,amount})).sort((a,b)=>b.amount-a.amount);return{total,count:economicRows.length,categories};},[economicRows]);

  return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 text-slate-100">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-rose-300">Gastos</p><h2 className="mt-1 text-lg font-black capitalize">{monthName(month)}</h2><p className="mt-1 text-xs text-slate-500">Escolha entre o fato econômico e seus impactos financeiros, sem contar o mesmo gasto duas vezes.</p></div><label className="text-xs text-slate-400">Mês<input type="month" value={month} onChange={event=>setMonth(event.target.value)} className="mt-1 min-h-10 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm text-slate-100"/></label></header>
    <div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-slate-950 p-1"><button type="button" onClick={()=>setMode('economic')} aria-pressed={mode==='economic'} className={`min-h-12 rounded-lg px-2 text-xs font-semibold ${mode==='economic'?'bg-blue-700 text-white':'text-slate-400'}`}>Gastos realizados</button><button type="button" onClick={()=>setMode('financial')} aria-pressed={mode==='financial'} className={`min-h-12 rounded-lg px-2 text-xs font-semibold ${mode==='financial'?'bg-blue-700 text-white':'text-slate-400'}`}>Compromissos do mês</button></div>
    {mode==='financial'&&<p className="mt-2 text-[11px] text-slate-500">O que impactou ou ainda deve impactar financeiramente este mês. A borda coral indica impacto ainda esperado.</p>}
    {mode==='economic'&&<p className="mt-2 text-[11px] text-slate-500">Com o que gastamos neste mês? Compras parceladas aparecem uma vez, pelo valor econômico total na data da compra.</p>}

    {loading?<div className="flex min-h-24 items-center justify-center"><LoaderCircle className="h-5 w-5 animate-spin text-blue-300"/></div>:error?<div className="mt-4 rounded-xl border border-rose-900 bg-rose-950/30 p-3"><p role="alert" className="text-xs text-rose-200">Não foi possível conferir este mês. Nenhum valor antigo foi mantido na tela.</p><button type="button" onClick={()=>setRefreshVersion(value=>value+1)} className="mt-2 min-h-10 rounded-lg border border-rose-800 px-3 text-xs font-semibold text-rose-200">Tentar novamente</button></div>:mode==='financial'?financialRows.length===0?<Empty text="Nenhum compromisso neste mês."/>:<><FinancialMonthSummary total={financialSummary.total} realized={financialSummary.realized} remaining={financialSummary.remaining}/><div className="mt-4 space-y-2">{financialRows.map(row=>{const pending=Number(row.remaining_amount)>0;return <article key={row.commitment_key} className={`rounded-xl border bg-slate-950/60 p-3 ${pending?'border-orange-500/80':'border-slate-800'}`}><div className="flex items-start gap-3"><CalendarDays className="mt-0.5 h-4 w-4 shrink-0 text-blue-300"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><h3 className="truncate text-sm font-bold">{row.description}</h3><p className="mt-1 text-[11px] text-slate-500">{sourceLabel(row)}{stateLabel(row.commitment_state)?` · ${stateLabel(row.commitment_state)}`:''}{row.due_date?` · vence ${row.due_date}`:''}</p></div><strong className="shrink-0 text-sm">{money(row.effective_amount)}</strong></div>{pending&&<p className="mt-2 text-[11px] text-amber-300">Ainda compromete {money(row.remaining_amount)}</p>}{row.source_type==='card_installment'&&<p className="mt-1 text-[11px] text-violet-300">Item da fatura; o pagamento não vira outro gasto.</p>}</div></div></article>})}</div></>:economicRows.length===0?<Empty text="Nenhum gasto realizado neste mês."/>:<><EconomicMonthSummary total={economicSummary.total} count={economicSummary.count} categories={economicSummary.categories}/><div className="mt-4 space-y-2">{economicRows.map(row=><article key={row.id} className="rounded-xl border border-slate-800 bg-slate-950/60 p-3"><div className="flex items-start gap-3"><ReceiptText className="mt-0.5 h-4 w-4 shrink-0 text-rose-300"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><h3 className="truncate text-sm font-bold">{row.description}</h3><p className="mt-1 text-[11px] text-slate-500">Compra em {row.transaction_date}{row.category?.name?` · ${row.category.name}`:''}</p></div><strong className="shrink-0 text-sm text-rose-200">{money(row.amount)}</strong></div></div></div></article>)}</div></>}
  </section>;
}

function FinancialMonthSummary({total,realized,remaining}:{total:number;realized:number;remaining:number}){
  const realizedPct=percentage(realized,total);
  return <div className="mt-4 rounded-2xl border border-slate-800 bg-slate-950/55 p-4"><div className="flex items-end justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">Visão dos compromissos</p><strong className="mt-1 block text-2xl">{money(total)}</strong><p className="text-[11px] text-slate-500">Total financeiro conhecido para o mês.</p></div><span className="rounded-full bg-slate-900 px-3 py-1 text-xs font-bold text-slate-300">{Math.round(realizedPct)}% realizado</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-400" style={{width:`${barWidth(realized,total)}%`}}/></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-emerald-950/20 p-3"><p className="text-[11px] text-emerald-300">Já realizado/pago</p><strong className="mt-1 block">{money(realized)}</strong></div><div className="rounded-xl bg-amber-950/20 p-3"><p className="text-[11px] text-amber-300">Ainda comprometido</p><strong className="mt-1 block">{money(remaining)}</strong></div></div></div>;
}

function EconomicMonthSummary({total,count,categories}:{total:number;count:number;categories:CategorySummary[]}){
  return <div className="mt-4 rounded-2xl border border-slate-800 bg-slate-950/55 p-4"><div className="flex items-end justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">Gasto realizado no mês</p><strong className="mt-1 block text-2xl text-rose-200">{money(total)}</strong></div><span className="rounded-full bg-slate-900 px-3 py-1 text-xs font-bold text-slate-300">{count} {count===1?'compra':'compras'}</span></div><div className="mt-5"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-bold">Por categoria</h3><span className="text-[10px] text-slate-500">participação no gasto</span></div><div className="mt-3 space-y-3">{categories.map(category=><div key={category.name}><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="truncate text-slate-300">{category.name}</span><span className="shrink-0 font-semibold">{money(category.amount)} · {Math.round(percentage(category.amount,total))}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-rose-400" style={{width:`${barWidth(category.amount,total)}%`}}/></div></div>)}</div><p className="mt-4 text-[10px] text-slate-500">Esta leitura mostra onde o dinheiro foi gasto. Não representa meta ou orçamento planejado.</p></div></div>;
}

function Empty({text}:{text:string}){return <p className="mt-4 rounded-xl border border-dashed border-slate-700 p-5 text-center text-xs text-slate-500">{text}</p>}
