import { useState, type FormEvent } from 'react';
import { History, Pencil, XCircle } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { listHouseholdCategories, type HouseholdCategory } from '../../finance/householdCategories.js';
import { listTransactionAdjustmentEvents, transactionAvailableActions, type HouseholdTransaction, type TransactionAdjustmentEvent } from '../../finance/householdTransactions.js';
import { cancelIncomeFact, correctIncomeFact } from '../../finance/incomeFacts.js';
import { FinancialDetailActionGroup } from './FinancialDetailActionGroup.js';

const normalizeAmount=(value:string)=>value.trim().replace(/\./g,'').replace(',','.');
const money=(value:string|null)=>Number(value??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const eventLabel={correction:'Correção',cancellation:'Cancelamento',refund:'Estorno'} as const;

export function IncomeFactManagement({transaction,onChanged}:{transaction:HouseholdTransaction;onChanged?:()=>void}){
  const{household}=useSupabaseAuth();const actions=transactionAvailableActions(transaction);const[editing,setEditing]=useState(false);const[historyOpen,setHistoryOpen]=useState(false);const[categories,setCategories]=useState<HouseholdCategory[]>([]);const[events,setEvents]=useState<TransactionAdjustmentEvent[]>([]);const[description,setDescription]=useState(transaction.description);const[amount,setAmount]=useState(String(transaction.amount??'').replace('.',','));const[date,setDate]=useState(transaction.transaction_date);const[categoryId,setCategoryId]=useState(transaction.category_id??'');const[reason,setReason]=useState('Correção informada pelo usuário');const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);

  const openEdit=async()=>{if(!supabase||!household)return;setError(null);try{const rows=await listHouseholdCategories(supabase,household.id);setCategories(rows.filter(row=>row.type==='income'));setEditing(true);}catch{setError('Não foi possível carregar as categorias para editar esta renda.');}};
  const openHistory=async()=>{if(!supabase||!household)return;setError(null);try{setEvents(await listTransactionAdjustmentEvents(supabase,household.id,transaction.id));setHistoryOpen(value=>!value);}catch{setError('Não foi possível carregar o histórico desta renda.');}};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!supabase||!household)return;const normalized=normalizeAmount(amount);if(!description.trim()||Number(normalized)<=0||!date||!reason.trim()){setError('Preencha descrição, valor, data e motivo da correção.');return;}setSaving(true);setError(null);try{await correctIncomeFact(supabase,{householdId:household.id,transactionId:transaction.id,description,amount:normalized,expectedDate:date,categoryId:categoryId||null,reason});setEditing(false);onChanged?.();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível corrigir a renda.');}finally{setSaving(false);}};
  const cancel=async()=>{if(!supabase||!household)return;const cancelReason=window.prompt('Por que esta renda prevista/confirmada foi cancelada?');if(!cancelReason?.trim())return;setSaving(true);setError(null);try{await cancelIncomeFact(supabase,{householdId:household.id,transactionId:transaction.id,reason:cancelReason});onChanged?.();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível cancelar a renda.');}finally{setSaving(false);}};

  return <div className="mt-3 border-t border-slate-800 pt-3"><FinancialDetailActionGroup primary={<>{actions.canEdit&&<button type="button" onClick={openEdit} className="flex min-h-10 items-center gap-1 rounded-lg border border-slate-700 px-3 text-xs font-bold text-blue-200"><Pencil className="h-3.5 w-3.5"/>Corrigir</button>}<button type="button" onClick={openHistory} className="flex min-h-10 items-center gap-1 rounded-lg border border-slate-700 px-3 text-xs font-bold text-slate-300"><History className="h-3.5 w-3.5"/>Histórico</button></>} secondary={actions.canCancel?<button type="button" disabled={saving} onClick={cancel} className="flex min-h-10 w-full items-center gap-2 rounded-lg border border-rose-900 px-3 text-xs font-bold text-rose-200"><XCircle className="h-3.5 w-3.5"/>Cancelar previsão</button>:undefined}/>
    {!actions.canEdit&&transaction.mutation_dependencies.has_recurring_occurrence&&<p className="mt-2 text-xs text-slate-500">Esta renda pertence a uma recorrência. Alterações futuras são feitas na gestão da série para preservar a história das ocorrências.</p>}
    {editing&&<form onSubmit={submit} className="mt-3 grid gap-2 rounded-xl border border-slate-700 bg-slate-950 p-3"><p className="text-xs text-slate-400">A correção atualiza o fato econômico e a perna projetada de caixa juntas. Não cria uma segunda renda.</p><label className="text-xs font-semibold">Descrição<input value={description} onChange={e=>setDescription(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg bg-slate-900 px-3"/></label><div className="grid grid-cols-2 gap-2"><label className="text-xs font-semibold">Valor<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" className="mt-1 min-h-10 w-full rounded-lg bg-slate-900 px-3"/></label><label className="text-xs font-semibold">Data esperada<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg bg-slate-900 px-3"/></label></div><label className="text-xs font-semibold">Categoria <span className="font-normal text-slate-500">(opcional)</span><select value={categoryId} onChange={e=>setCategoryId(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg bg-slate-900 px-3"><option value="">Sem categoria</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-xs font-semibold">Motivo da correção<input value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg bg-slate-900 px-3"/></label><div className="flex gap-2"><button disabled={saving} className="min-h-10 rounded-lg bg-blue-600 px-3 text-xs font-bold">Salvar correção</button><button type="button" onClick={()=>setEditing(false)} className="min-h-10 rounded-lg border border-slate-700 px-3 text-xs">Fechar</button></div></form>}
    {historyOpen&&<div className="mt-3 rounded-xl border border-slate-800 bg-slate-950 p-3"><h4 className="text-xs font-bold uppercase tracking-wide text-slate-400">História desta renda</h4>{events.length===0?<p className="mt-2 text-xs text-slate-500">Nenhuma correção ou cancelamento registrado.</p>:<div className="mt-2 space-y-2">{events.map(event=><article key={event.id} className="text-xs"><strong>{eventLabel[event.kind]}</strong><span className="text-slate-500"> · {new Date(event.occurred_at).toLocaleString('pt-BR')}</span><p className="text-slate-400">{event.reason}{event.amount?` · ${money(event.amount)}`:''}</p></article>)}</div>}</div>}
    {error&&<p role="alert" className="mt-2 text-xs text-rose-300">{error}</p>}
  </div>;
}
