import { useEffect, useState } from 'react';
import { LoaderCircle, ReceiptText } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { listHouseholdTransactions, type HouseholdTransaction } from '../../finance/householdTransactions.js';
import { ensureRecurringIncomeHorizon } from '../../finance/recurringIncome.js';
import { IncomeCreationAction } from './IncomeCreationAction.js';
import { IncomeReceiptAction } from './IncomeReceiptAction.js';
import { RecurringIncomeAction } from './RecurringIncomeAction.js';
import { RecurringIncomeManagement } from './RecurringIncomeManagement.js';
import { IncomeFactManagement } from './IncomeFactManagement.js';

const money=(value:string)=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const stateLabel:Record<string,string>={forecast:'Prevista',confirmed:'Confirmada',realized:'Realizada',cancelled:'Cancelada',reversed:'Estornada'};
const horizonDate=()=>{const date=new Date();date.setFullYear(date.getFullYear()+1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;};

export function IncomeLedgerScreen({initialMoneyMovementId,initialReviewMoneyMovementId}:{initialMoneyMovementId?:string;initialReviewMoneyMovementId?:string}){
 const{household}=useSupabaseAuth();const[rows,setRows]=useState<HouseholdTransaction[]>([]);const[loading,setLoading]=useState(true);const[refreshKey,setRefreshKey]=useState(0);const[error,setError]=useState<string|null>(null);const[reviewTransactionId,setReviewTransactionId]=useState<string|null>(null);
 useEffect(()=>{if(!supabase||!household)return;let active=true;setLoading(true);setError(null);setReviewTransactionId(null);const load=async()=>{try{try{await ensureRecurringIncomeHorizon(supabase!,household.id,horizonDate());}catch(error){console.warn('Casa Finance: não foi possível atualizar o horizonte de rendas recorrentes antes de listar Entradas.',error);}const [transactions,movement]=await Promise.all([listHouseholdTransactions(supabase!,household.id),initialReviewMoneyMovementId?supabase!.from('money_movements').select('related_transaction_id').eq('household_id',household.id).eq('id',initialReviewMoneyMovementId).maybeSingle():Promise.resolve({data:null,error:null})]);if(movement.error)throw movement.error;const incomeRows=transactions.filter(row=>row.type==='income');if(!active)return;setRows(incomeRows);if(initialReviewMoneyMovementId){const target=incomeRows.find(row=>row.id===movement.data?.related_transaction_id);if(target)setReviewTransactionId(target.id);}}catch{if(active){setRows([]);setError('Não foi possível carregar as rendas da Casa. Nenhuma renda foi presumida como ausente ou resolvida.');}}finally{if(active)setLoading(false);}};void load();return()=>{active=false;};},[household?.id,refreshKey,initialReviewMoneyMovementId]);
 const refresh=()=>setRefreshKey(value=>value+1);
 return <div className="space-y-5">
  <header><h1 className="text-2xl font-black">Entradas</h1><p className="mt-1 text-sm text-slate-400">O que entra de verdade na Casa, o que ainda está previsto e o que já caiu na conta.</p></header>
  {!loading&&!error&&initialReviewMoneyMovementId&&<p className={`rounded-xl border p-3 text-xs ${reviewTransactionId?'border-cyan-900 bg-cyan-950/20 text-cyan-200':'border-slate-700 bg-slate-900 text-slate-300'}`}>{reviewTransactionId?'Esta entrada futura foi sinalizada pela revisão da projeção. O Casa releu o movimento e o fato econômico atual. Revise ou corrija a previsão abaixo; nenhum recebimento foi registrado.':'A entrada sinalizada pela revisão da projeção mudou ou já foi resolvida. Nada entrou no caixa.'}</p>}
  {initialMoneyMovementId&&<IncomeReceiptAction initialMoneyMovementId={initialMoneyMovementId} onCompleted={refresh}/>} 
  <IncomeCreationAction onCreated={refresh}/>
  <section className="space-y-3"><div><h2 className="font-bold">Suas entradas</h2><p className="mt-1 text-xs text-slate-500">Aqui ficam rendas previstas, confirmadas e já recebidas. O Casa preserva o histórico quando algo precisa ser corrigido.</p></div>{loading?<LoaderCircle className="mx-auto h-5 w-5 animate-spin"/>:error?<p role="alert" className="rounded-2xl border border-rose-900 bg-rose-950/30 p-4 text-sm text-rose-200">{error}</p>:rows.length===0?<div className="rounded-2xl border border-dashed border-slate-700 p-6 text-center"><p className="text-sm font-semibold text-slate-300">Ainda não há entradas por aqui.</p><p className="mt-1 text-xs text-slate-500">Quando você cadastrar salário, aluguel, freelance ou outra renda verdadeira, ela aparece nesta lista.</p></div>:rows.map(row=>{const targeted=row.id===reviewTransactionId;return <article key={row.id} className={`rounded-2xl border bg-slate-900 p-4 ${targeted?'border-cyan-500 ring-1 ring-cyan-500/40':'border-slate-800'}`}><div className="flex items-start gap-3"><ReceiptText className="mt-0.5 h-5 w-5 text-emerald-300"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><h3 className="font-bold">{row.description}</h3>{targeted&&<span className="mt-1 inline-block rounded-full bg-cyan-950 px-2 py-1 text-[10px] font-bold text-cyan-300">Revisar projeção</span>}</div><strong className="text-emerald-300">+ {money(row.amount)}</strong></div><p className="mt-1 text-sm text-slate-400">{row.transaction_date} · {row.category?.name??'Sem categoria'}</p><p className="mt-1 text-xs font-semibold text-emerald-300">{stateLabel[row.economic_state]??row.economic_state} · recebido {money(row.realized_amount)}</p><IncomeFactManagement transaction={row} onChanged={refresh}/></div></div></article>})}</section>
  <details className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4">
   <summary className="cursor-pointer list-none font-semibold text-slate-200">Recorrências e outras ações<span className="mt-1 block text-xs font-normal text-slate-500">Use quando quiser configurar uma renda que se repete, gerenciar uma série ou confirmar manualmente um recebimento.</span></summary>
   <div className="mt-4 space-y-4 border-t border-slate-800 pt-4"><RecurringIncomeAction onCreated={refresh}/><RecurringIncomeManagement refreshKey={refreshKey} onChanged={refresh}/>{!initialMoneyMovementId&&<IncomeReceiptAction initialMoneyMovementId={undefined} onCompleted={refresh}/>}</div>
  </details>
 </div>;
}
