import { useEffect, useState, type FormEvent } from 'react';
import { CalendarClock, LoaderCircle } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { closeRecurringIncomeRule, listRecurringIncomeRules, reviseRecurringIncomeRule, type RecurringIncomeFrequency, type RecurringIncomeRule } from '../../finance/recurringIncome.js';

const localDate = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`; };
const money = (value: string) => Number(value).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const normalizeAmount = (value: string) => value.trim().replace(/\./g, '').replace(',', '.');

export function RecurringIncomeManagement({ refreshKey, onChanged, focusRuleId }: { refreshKey: number; onChanged?: () => void; focusRuleId?: string | null }) {
  const { household } = useSupabaseAuth();
  const [rules, setRules] = useState<RecurringIncomeRule[]>([]); const [selected, setSelected] = useState<RecurringIncomeRule | null>(null); const [mode, setMode] = useState<'revise' | 'close' | null>(null);
  const [effectiveFrom, setEffectiveFrom] = useState(localDate()); const [amount, setAmount] = useState(''); const [frequency, setFrequency] = useState<RecurringIncomeFrequency>('monthly'); const [endDate, setEndDate] = useState(''); const [reason, setReason] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [loadError, setLoadError] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  const clearLoadedContext=()=>{setRules([]);setSelected(null);setMode(null);};
  const load=async()=>{if(!supabase||!household)return;setLoading(true);setLoadError(null);setError(null);try{const loaded=await listRecurringIncomeRules(supabase,household.id);setRules(loaded);if(focusRuleId&&!loaded.some(rule=>rule.id===focusRuleId))setLoadError('Esta recorrência não está mais ativa.');}catch{clearLoadedContext();setLoadError('Não foi possível conferir as entradas que se repetem. Nenhuma delas pode ser alterada ou encerrada até uma nova leitura válida.');}finally{setLoading(false);}};
  useEffect(() => { void load(); }, [household?.id, refreshKey, focusRuleId]);
  const open = (rule: RecurringIncomeRule, nextMode: 'revise' | 'close') => { setSelected(rule); setMode(nextMode); setEffectiveFrom(localDate()); setAmount(rule.estimated_amount); setFrequency(rule.frequency); setEndDate(rule.end_date ?? ''); setReason(''); setError(null); setSuccess(null); };
  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if(loadError){setError('Confira novamente as entradas recorrentes antes de mudar os próximos meses.');return;}
    if (!supabase || !household || !selected || !mode) return;
    if (effectiveFrom < localDate()) { setError('A mudança precisa começar hoje ou em uma data futura.'); return; }
    if (!reason.trim()) { setError('Conte o motivo da mudança. Assim você consegue entender depois o que aconteceu.'); return; }
    setSaving(true); setError(null); setSuccess(null);
    try {
      if (mode === 'close') { await closeRecurringIncomeRule(supabase, household.id, selected.id, effectiveFrom, reason); setSuccess('Entrada recorrente encerrada a partir da data escolhida. O que já aconteceu continua preservado.'); }
      else { const normalized = normalizeAmount(amount); if (!Number.isFinite(Number(normalized)) || Number(normalized) <= 0) throw new Error('Informe um valor maior que zero.'); if (endDate && endDate < effectiveFrom) throw new Error('A data final não pode ser anterior ao início da mudança.'); await reviseRecurringIncomeRule(supabase, household.id, selected, { effectiveFrom, amount: normalized, frequency, endDate, reason }); setSuccess('Mudança salva para os próximos meses. Entradas anteriores e valores já recebidos continuam como estavam.'); }
      setSelected(null); setMode(null); onChanged?.();
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível alterar esta entrada recorrente.'); }
    finally { setSaving(false); }
  };
  const visibleRules=focusRuleId?rules.filter(rule=>rule.id===focusRuleId):rules;
  return <section className="rounded-2xl border border-slate-700 bg-slate-900/70 p-4">
    <div className="flex items-start gap-3"><CalendarClock className="mt-0.5 h-5 w-5 text-emerald-300"/><div><h2 className="font-bold">{focusRuleId?'Gerenciar esta recorrência':'Entradas que se repetem'}</h2><p className="mt-1 text-sm text-slate-400">{focusRuleId?'Mudanças valem somente daqui para frente; o que já aconteceu permanece preservado.':'Salário, aluguel e outras entradas recorrentes podem mudar daqui para frente sem alterar os meses que já passaram nem valores que você já recebeu.'}</p></div></div>
    {!loadError&&error && <p role="alert" className="mt-3 text-sm text-rose-300">{error}</p>}{success && <p role="status" className="mt-3 text-sm text-emerald-300">{success}</p>}
    {loading ? <LoaderCircle className="mx-auto mt-4 h-5 w-5 animate-spin"/> : loadError ? <div className="mt-4 rounded-xl border border-rose-900 bg-rose-950/30 p-3"><p role="alert" className="text-sm text-rose-200">{loadError}</p><button type="button" onClick={()=>void load()} className="mt-3 min-h-11 rounded-xl border border-rose-800 px-3 text-sm font-semibold text-rose-200">Tentar novamente</button></div> : <div className="mt-4 space-y-3">{visibleRules.length === 0 ? <p className="text-sm text-slate-400">Nenhuma entrada recorrente ativa.</p> : visibleRules.map((rule) => <article key={rule.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex items-start justify-between gap-3"><div><strong>{rule.income_description}</strong><p className="mt-1 text-xs text-slate-400">{money(rule.estimated_amount)} · {rule.frequency === 'monthly' ? 'todo mês' : 'todo ano'} · desde {rule.start_date}</p></div><div className="flex gap-2"><button type="button" onClick={() => open(rule,'revise')} className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-bold">Mudar próximos meses</button><button type="button" onClick={() => open(rule,'close')} className="rounded-lg border border-rose-900 px-3 py-2 text-xs font-bold text-rose-300">Parar recorrência</button></div></div></article>)}</div>}
    {!loadError&&selected && mode && <form onSubmit={submit} className="mt-4 grid gap-3 rounded-xl border border-emerald-900/60 bg-emerald-950/10 p-3"><h3 className="font-bold">{mode === 'revise' ? `Mudar ${selected.income_description} nos próximos meses` : `Parar ${selected.income_description}`}</h3><label className="text-sm font-semibold">A partir de quando?<input type="date" value={effectiveFrom} onChange={(e) => setEffectiveFrom(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-slate-950 px-3"/></label>{mode === 'revise' && <><label className="text-sm font-semibold">Qual será o novo valor?<input value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="decimal" className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-slate-950 px-3"/></label><label className="text-sm font-semibold">Com que frequência?<select value={frequency} onChange={(e) => setFrequency(e.target.value as RecurringIncomeFrequency)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-slate-950 px-3"><option value="monthly">Todo mês</option><option value="yearly">Todo ano</option></select></label><label className="text-sm font-semibold">Até quando? (opcional)<input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-slate-950 px-3"/></label></>}<label className="text-sm font-semibold">Por que está mudando?<textarea value={reason} onChange={(e) => setReason(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Ex.: reajuste salarial, fim do contrato de aluguel…"/></label><div className="flex gap-2"><button disabled={saving} className="min-h-11 rounded-xl bg-emerald-600 px-4 font-bold disabled:opacity-50">{saving ? 'Salvando…' : mode === 'revise' ? 'Salvar mudança' : 'Parar recorrência'}</button><button type="button" onClick={() => { setSelected(null); setMode(null); }} className="min-h-11 rounded-xl border border-slate-700 px-4 font-bold">Cancelar</button></div></form>}
  </section>;
}
