import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { BellRing, LoaderCircle } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { listHouseholdFinancialAccounts } from '../../finance/householdFinancialAccounts.js';
import type { RecurringExpenseActionIntent, RecurringExpenseActionMode } from '../../finance/recurringExpenseIntent.js';
import { confirmRecurringCardExpenseOccurrence, confirmRecurringExpenseOccurrence, listRecurringExpenseCommitments, settleRecurringExpenseOccurrence, type RecurringExpenseCommitment } from '../../finance/recurringExpenseCommitments.js';

const transactionalTypes = new Set(['cash','checking','savings','digital_wallet']);
const money = (value: string|number) => Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const localDateTime = () => { const now=new Date(); const local=new Date(now.getTime()-now.getTimezoneOffset()*60000); return local.toISOString().slice(0,16); };
const stateLabel = { overdue:'Vencida', due_today:'Vence hoje', due_soon:'Vence em breve', upcoming:'Próximos 7 dias' } as const;

export function RecurringExpenseCommitmentCenter({ onChanged, initialIntent }: { onChanged?: () => void; initialIntent?: RecurringExpenseActionIntent | null }) {
  const { household, householdMembers } = useSupabaseAuth();
  const [items,setItems]=useState<RecurringExpenseCommitment[]>([]); const [accounts,setAccounts]=useState<Array<{id:string;name:string;type:string}>>([]);
  const [selectedId,setSelectedId]=useState(''); const [mode,setMode]=useState<RecurringExpenseActionMode|null>(null); const [amount,setAmount]=useState(''); const [accountId,setAccountId]=useState(''); const [funderMemberId,setFunderMemberId]=useState(''); const [paidAt,setPaidAt]=useState(localDateTime());
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [loadError,setLoadError]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);
  const handledIntent=useRef(false); const selected=useMemo(()=>items.find((item)=>item.occurrence_id===selectedId)??null,[items,selectedId]);
  const clearLoadedContext=()=>{setItems([]);setAccounts([]);setSelectedId('');setMode(null);setAmount('');setAccountId('');setFunderMemberId('');};
  const load=async()=>{ if(!supabase||!household)return; setLoading(true); setLoadError(null); setError(null); try { const [commitments,financial]=await Promise.all([listRecurringExpenseCommitments(supabase,household.id),listHouseholdFinancialAccounts(supabase,household.id)]); setItems(commitments); setAccounts(financial.accounts.filter((account)=>transactionalTypes.has(account.type))); } catch { clearLoadedContext(); setLoadError('Não foi possível conferir as contas recorrentes e as contas da Casa. Nenhuma previsão ou pagamento pode ser alterado até uma nova leitura válida.'); } finally { setLoading(false); } };
  useEffect(()=>{load();},[household?.id]);
  const open=(item:RecurringExpenseCommitment,next:RecurringExpenseActionMode)=>{setSelectedId(item.occurrence_id);setMode(next);setAmount(item.remaining_amount);setAccountId(item.planned_account_id??'');setFunderMemberId('');setPaidAt(localDateTime());setError(null);setSuccess(null);};
  useEffect(()=>{if(loading||loadError||handledIntent.current||!initialIntent)return;handledIntent.current=true;const target=items.find((item)=>item.occurrence_id===initialIntent.occurrenceId);if(target)open(target,initialIntent.mode);else setError('Essa conta mudou ou já foi resolvida. O Casa atualizou a lista antes de permitir qualquer ação.');},[loading,loadError,items,initialIntent]);
  const close=()=>{setSelectedId('');setMode(null);};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(loadError){setError('Confira novamente as contas recorrentes antes de confirmar ou pagar.');return;}if(!supabase||!household||!selected||!mode)return;const parsed=Number(amount.replace(',','.'));if(!Number.isFinite(parsed)||parsed<=0){setError('Informe um valor maior que zero.');return;}if(parsed>Number(selected.remaining_amount)){setError('O valor não pode ser maior do que ainda falta pagar nesta conta.');return;}if(mode==='pay'&&!accountId){setError('Informe de qual conta o dinheiro realmente saiu.');return;}if(mode==='pay'&&!funderMemberId){setError('Informe quem pagou com o próprio dinheiro.');return;}setSaving(true);setError(null);setSuccess(null);try{if(mode==='confirm'){if(selected.payment_instrument_kind==='card'){await confirmRecurringCardExpenseOccurrence(supabase,household.id,selected.occurrence_id,parsed.toFixed(2));setSuccess('Cobrança confirmada no cartão. Ela entrou na fatura e no limite; nenhum dinheiro saiu de uma conta.');}else{await confirmRecurringExpenseOccurrence(supabase,household.id,selected.occurrence_id,parsed.toFixed(2));setSuccess('Valor desta conta atualizado na previsão. Nenhum dinheiro saiu de uma conta agora.');}}else{await settleRecurringExpenseOccurrence(supabase,{householdId:household.id,occurrenceId:selected.occurrence_id,accountId,funderMemberId,amount:parsed.toFixed(2),paidAt:new Date(paidAt).toISOString()});setSuccess(accountId===selected.planned_account_id?'Pagamento registrado. O saldo agora considera a saída que realmente aconteceu.':'Pagamento registrado por outra conta. A conta planejada foi preservada e o dinheiro saiu somente da conta informada.');}close();await load();onChanged?.();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível atualizar esta conta recorrente.');}finally{setSaving(false);}};
  return <section className="rounded-2xl border border-amber-900/60 bg-amber-950/10 p-4">
    <div className="flex items-start gap-3"><BellRing className="mt-0.5 h-5 w-5 text-amber-300"/><div><h2 className="font-bold">Recorrências previstas</h2><p className="mt-1 text-sm text-slate-400">Contas só alteram caixa ao registrar o pagamento. Cobranças recorrentes no cartão só usam limite quando a cobrança é confirmada e depois são pagas exclusivamente pela fatura.</p></div></div>
    <p className="mt-3 rounded-xl border border-blue-900/60 bg-blue-950/20 p-3 text-xs text-blue-200">A conta mostrada aqui é a que você imaginava usar. Se pagar por outra conta, basta informar qual foi usada de verdade.</p>
    {loading?<LoaderCircle className="mx-auto mt-4 h-5 w-5 animate-spin"/>:loadError?<div className="mt-4 rounded-xl border border-rose-900 bg-rose-950/30 p-3"><p role="alert" className="text-sm text-rose-200">{loadError}</p><button type="button" onClick={()=>void load()} className="mt-3 min-h-11 rounded-xl border border-rose-800 px-3 text-sm font-semibold text-rose-200">Tentar novamente</button></div>:items.length===0?<p className="mt-4 text-sm text-slate-400">Nenhuma recorrência vencida ou com vencimento nos próximos 7 dias.</p>:<div className="mt-4 space-y-3">{items.map((item)=><article key={item.occurrence_id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex items-start justify-between gap-3"><div><strong>{item.description}</strong><p className="mt-1 text-xs text-slate-400">{stateLabel[item.attention_state]} · {item.due_date}{item.payment_instrument_kind==='card'?' · cobrança prevista no cartão':item.planned_account_name?` · conta planejada: ${item.planned_account_name}`:''}</p><p className="mt-1 text-xs text-slate-500">Valor previsto: {money(item.expected_amount)} · falta pagar {money(item.remaining_amount)}</p></div><strong className="text-amber-200">{money(item.remaining_amount)}</strong></div><div className="mt-3 flex gap-2"><button type="button" onClick={()=>open(item,'confirm')} className="min-h-10 rounded-lg border border-slate-700 px-3 text-xs font-bold">{item.payment_instrument_kind==='card'?'Confirmar cobrança':'Conferir valor'}</button>{item.payment_instrument_kind==='account'&&<button type="button" onClick={()=>open(item,'pay')} className="min-h-10 rounded-lg bg-emerald-500 px-3 text-xs font-bold text-slate-950">Registrar pagamento</button>}</div></article>)}</div>}
    {!loadError&&selected&&mode&&<form onSubmit={submit} className="mt-4 grid gap-3 rounded-xl border border-amber-900 bg-slate-950 p-3"><div><strong>{mode==='confirm'?(selected.payment_instrument_kind==='card'?'Confirmar cobrança no cartão':'Conferir valor desta conta'):'Como esta conta foi paga?'}</strong><p className="text-xs text-slate-400">{selected.description} · esta alteração vale só para esta conta deste mês; os próximos meses não mudam.</p></div><label className="text-sm font-semibold">Quanto é esta conta?<input value={amount} onChange={(e)=>setAmount(e.target.value)} inputMode="decimal" className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3"/></label>{mode==='pay'&&<><label className="text-sm font-semibold">De qual conta o dinheiro saiu?<select value={accountId} onChange={(e)=>setAccountId(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3"><option value="">Selecione</option>{accounts.map((account)=><option key={account.id} value={account.id}>{account.name}{account.id===selected.planned_account_id?' · planejada':''}</option>)}</select></label><label className="text-sm font-semibold">Quem pagou com o próprio dinheiro?<select value={funderMemberId} onChange={(e)=>setFunderMemberId(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3"><option value="">Selecione</option>{householdMembers.map((member)=><option key={member.id} value={member.id}>{member.display_name}</option>)}</select></label><label className="text-sm font-semibold">Quando foi pago?<input type="datetime-local" value={paidAt} onChange={(e)=>setPaidAt(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3"/></label></>}{error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}<div className="flex gap-2"><button disabled={saving} className="min-h-11 flex-1 rounded-xl bg-amber-500 px-4 font-bold text-slate-950 disabled:opacity-50">{saving?'Salvando…':mode==='confirm'?(selected.payment_instrument_kind==='card'?'Confirmar cobrança':'Atualizar valor'):'Registrar pagamento'}</button><button type="button" onClick={close} className="min-h-11 rounded-xl border border-slate-700 px-4">Cancelar</button></div></form>}
    {!selected&&success&&<p role="status" className="mt-3 text-sm text-emerald-300">{success}</p>}{!loadError&&!selected&&error&&<p role="alert" className="mt-3 text-sm text-rose-300">{error}</p>}
  </section>;
}
