import { useState } from 'react';
import { ArrowLeft, CreditCard, FolderTree, LogOut, Users } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { HouseholdFinancialSetup } from '../auth/HouseholdFinancialSetup.js';
import { HouseholdCategoriesSetup } from '../auth/HouseholdCategoriesSetup.js';
import { FinancialPartiesSettings } from './FinancialPartiesSettings.js';
type Area='menu'|'financial'|'categories';
export function SettingsScreen(){const{household,householdMembers,signOut,isSubmitting}=useSupabaseAuth();const[area,setArea]=useState<Area>('menu');if(area==='financial')return <div><Back onClick={()=>setArea('menu')}/><HouseholdFinancialSetup/></div>;if(area==='categories')return <HouseholdCategoriesSetup onBack={()=>setArea('menu')}/>;return <div className="space-y-5"><header><p className="text-xs font-bold uppercase tracking-widest text-purple-400">Configurações</p><h1 className="mt-1 text-2xl font-black">Ajustes</h1><p className="mt-1 text-sm text-slate-400">Gerencie {household?.name} e suas estruturas financeiras.</p></header><section className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h2 className="flex items-center gap-2 font-bold"><Users className="h-5 w-5 text-purple-400"/>Casa e membros</h2><ul className="mt-3 space-y-2">{householdMembers.map(member=><li key={member.id} className="flex justify-between rounded-xl bg-slate-950 p-3 text-sm"><span>{member.display_name}</span><span className="text-slate-500">{member.role==='owner'?'Proprietário':'Membro'}</span></li>)}</ul>{householdMembers.length<2&&<p className="mt-3 text-xs text-slate-500">Convites podem ser gerenciados no fluxo da Casa.</p>}</section><FinancialPartiesSettings/><button onClick={()=>setArea('financial')} className="flex min-h-14 w-full items-center gap-3 rounded-2xl border border-slate-800 bg-slate-900 px-4 font-semibold"><CreditCard className="h-5 w-5 text-blue-400"/>Contas, cartões e posição inicial</button><button onClick={()=>setArea('categories')} className="flex min-h-14 w-full items-center gap-3 rounded-2xl border border-slate-800 bg-slate-900 px-4 font-semibold"><FolderTree className="h-5 w-5 text-emerald-400"/>Categorias</button><button onClick={signOut} disabled={isSubmitting} className="flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl border border-rose-900 font-semibold text-rose-300"><LogOut className="h-5 w-5"/>Sair da conta</button></div>}
function Back({onClick}:{onClick:()=>void}){return <button onClick={onClick} className="mb-3 flex min-h-11 items-center gap-2 text-sm font-semibold text-blue-300"><ArrowLeft className="h-4 w-4"/>Voltar aos ajustes</button>}
