import { useEffect, useMemo, useState } from 'react';
import { HandCoins, LoaderCircle, UsersRound } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { listMemberSettlementEvents, listMemberSettlementPositions, type MemberSettlementEvent, type MemberSettlementPosition } from '../../finance/memberSettlements.js';
import { listOpenThirdPartyObligations, type ThirdPartyObligation } from '../../finance/thirdPartyObligations.js';
import type { SettlementActionIntent } from '../../finance/settlementActionIntent.js';
import { FinancialSectionHeading } from './FinancialSectionHeading.js';

const money=(value:number|string)=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const dateLabel=(value:string|null)=>{if(!value)return 'Sem vencimento';const date=new Date(`${value}T12:00:00`);const today=new Date();today.setHours(0,0,0,0);date.setHours(0,0,0,0);if(date.getTime()<today.getTime())return `Venceu em ${date.toLocaleDateString('pt-BR')}`;if(date.getTime()===today.getTime())return 'Vence hoje';return `Vence em ${date.toLocaleDateString('pt-BR')}`;};

export function SettlementHub({onResolve}:{onResolve?:(intent:SettlementActionIntent)=>void}){
  const{household,householdMembers}=useSupabaseAuth();
  const[memberRows,setMemberRows]=useState<MemberSettlementPosition[]>([]);
  const[memberEvents,setMemberEvents]=useState<MemberSettlementEvent[]>([]);
  const[thirdPartyRows,setThirdPartyRows]=useState<ThirdPartyObligation[]>([]);
  const[loading,setLoading]=useState(true);
  const[error,setError]=useState(false);
  const[refreshKey,setRefreshKey]=useState(0);
  useEffect(()=>{let cancelled=false;if(!supabase||!household)return;setLoading(true);setError(false);Promise.all([listMemberSettlementPositions(supabase,household.id),listOpenThirdPartyObligations(supabase,household.id),listMemberSettlementEvents(supabase,household.id)]).then(([members,thirdParties,events])=>{if(cancelled)return;setMemberRows(members);setThirdPartyRows(thirdParties);setMemberEvents(events);}).catch(()=>{if(cancelled)return;setMemberRows([]);setThirdPartyRows([]);setMemberEvents([]);setError(true);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[household?.id,refreshKey]);
  const retry=()=>setRefreshKey(value=>value+1);
  const memberName=(id:string)=>householdMembers.find(member=>member.id===id)?.display_name??'Membro';
  const oppositeOf=(row:MemberSettlementPosition)=>memberRows.find(candidate=>candidate.debtor_member_id===row.creditor_member_id&&candidate.creditor_member_id===row.debtor_member_id);
  const realized=useMemo(()=>memberRows.filter(row=>Number(row.net_position)>0),[memberRows]);
  const projected=useMemo(()=>memberRows.filter(row=>Number(row.projected_outstanding)-Number(oppositeOf(row)?.projected_outstanding??0)>0),[memberRows]);
  const projectedNet=(row:MemberSettlementPosition)=>Math.max(0,Number(row.projected_outstanding)-Number(oppositeOf(row)?.projected_outstanding??0));
  const eventsFor=(row:MemberSettlementPosition,state:'realized'|'projected')=>memberEvents.filter(event=>event.state===state&&((event.debtor_member_id===row.debtor_member_id&&event.creditor_member_id===row.creditor_member_id)||(event.debtor_member_id===row.creditor_member_id&&event.creditor_member_id===row.debtor_member_id)));
  const eventLabel=(event:MemberSettlementEvent)=>event.source_money_movement_id&&event.kind==='adjustment'?'Transferência entre vocês':event.notes?.trim()||event.source_description||(event.kind==='explicit_settlement'?'Transferência já considerada':'Despesa ou compromisso que originou esta diferença');
  const eventImpact=(event:MemberSettlementEvent,row:MemberSettlementPosition)=>{const sameDirection=event.debtor_member_id===row.debtor_member_id&&event.creditor_member_id===row.creditor_member_id;const direction=sameDirection?1:-1;const kind=event.kind==='explicit_settlement'||event.kind==='correction'?-1:1;return Number(event.amount)*direction*kind;};
  const completedSettlements=useMemo(()=>memberEvents.filter(event=>event.state==='realized'&&Boolean(event.source_money_movement_id)&&(event.kind==='explicit_settlement'||event.kind==='adjustment')).slice(0,6),[memberEvents]);

  if(loading)return <section><FinancialSectionHeading title="Valores com pessoas" icon={<UsersRound className="h-5 w-5 text-cyan-400"/>}/><LoaderCircle className="h-5 w-5 animate-spin text-cyan-300"/></section>;
  return <section>
    <FinancialSectionHeading title="Valores com pessoas" icon={<UsersRound className="h-5 w-5 text-cyan-400"/>}/>
    {!error&&<button type="button" onClick={()=>onResolve?.({kind:'third-party-create'})} className="mb-4 min-h-10 rounded-xl border border-slate-700 px-3 text-sm font-semibold text-slate-300">Adicionar valor com outra pessoa</button>}
    {error&&<div className="rounded-xl border border-rose-900 bg-rose-950/30 p-3"><p role="alert" className="text-sm text-rose-200">Não foi possível conferir os valores com pessoas agora. O Casa limpou a leitura anterior e não vai presumir que uma posição foi resolvida ou que não há nada em aberto.</p><button type="button" onClick={retry} className="mt-3 min-h-10 rounded-xl border border-rose-800 px-3 text-sm font-semibold text-rose-200">Tentar novamente</button></div>}
    {!error&&realized.length===0&&thirdPartyRows.length===0&&projected.length===0&&<div className="rounded-2xl border border-dashed border-slate-800 p-4"><p className="text-sm font-semibold text-slate-300">Tudo equilibrado entre as pessoas por enquanto.</p><p className="mt-1 text-xs text-slate-500">Quando surgir uma diferença entre vocês ou um valor com outra pessoa, o Casa mostra aqui.</p></div>}
    {!error&&realized.length>0&&<div className="space-y-2"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Entre vocês · posição de hoje</p>{realized.map(row=><article key={`${row.debtor_member_id}-${row.creditor_member_id}`} className="rounded-2xl border border-slate-800 p-4"><div className="flex items-start justify-between gap-3"><div><b>{memberName(row.creditor_member_id)} tem a receber de {memberName(row.debtor_member_id)}</b><p className="mt-1 text-sm text-slate-400">Esta é a posição líquida realizada entre vocês neste momento.</p></div><strong className="whitespace-nowrap text-cyan-200">{money(row.net_position)}</strong></div><details className="mt-3 rounded-xl bg-slate-950/70 p-3"><summary className="cursor-pointer text-sm font-semibold text-slate-300">Ver de onde vem esse valor</summary><ul className="mt-2 space-y-2 text-xs text-slate-400">{eventsFor(row,'realized').map(event=><li key={event.id} className="flex justify-between gap-3"><span>{eventLabel(event)} · {new Date(`${event.financial_date}T12:00:00`).toLocaleDateString('pt-BR')}</span><strong className={eventImpact(event,row)<0?'text-emerald-300':'text-slate-200'}>{eventImpact(event,row)<0?'−':'+'}{money(Math.abs(eventImpact(event,row)))}</strong></li>)}</ul></details></article>)}</div>}
    {!error&&thirdPartyRows.length>0&&<div className="mt-4 space-y-2"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Com outras pessoas</p>{thirdPartyRows.map(row=><article key={row.id} className="rounded-2xl border border-slate-800 p-4"><div className="flex items-start justify-between gap-3"><div><b>{row.kind==='receivable'?`${row.counterparty_name} deve para a Casa`:`A Casa deve para ${row.counterparty_name}`}</b><p className="mt-1 text-sm text-slate-400">{row.description}</p><p className={`mt-1 text-xs ${row.due_date&&new Date(`${row.due_date}T12:00:00`).getTime()<Date.now()?'text-amber-300':'text-slate-500'}`}>{dateLabel(row.due_date)}</p></div><strong className="whitespace-nowrap text-cyan-200">{money(row.outstanding_amount)}</strong></div><button type="button" onClick={()=>onResolve?.({kind:'third-party',obligationId:row.id,amount:Number(row.outstanding_amount)})} className="mt-3 flex min-h-10 w-full items-center justify-center gap-2 rounded-xl border border-cyan-800 bg-cyan-950/30 px-3 text-sm font-bold text-cyan-200"><HandCoins className="h-4 w-4"/>{row.kind==='receivable'?'Registrar recebimento':'Registrar pagamento'}</button><details className="mt-2 rounded-xl border border-slate-800 px-3 py-2"><summary className="cursor-pointer text-xs font-semibold text-slate-400">Outras opções deste valor</summary><div className="mt-2 grid gap-2">{row.origin_kind==='manual'&&row.state==='open'&&row.settled_amount===0&&<button type="button" onClick={()=>onResolve?.({kind:'third-party-manage',obligationId:row.id})} className="min-h-10 rounded-lg border border-slate-700 px-3 text-left text-xs font-semibold text-slate-300">Corrigir cadastro ou vencimento</button>}{row.kind==='receivable'?<button type="button" onClick={()=>onResolve?.({kind:'third-party-loss',obligationId:row.id})} className="min-h-10 rounded-lg border border-rose-900 px-3 text-left text-xs font-semibold text-rose-300">Não será recebido</button>:<button type="button" onClick={()=>onResolve?.({kind:'third-party-forgiveness',obligationId:row.id})} className="min-h-10 rounded-lg border border-emerald-900 px-3 text-left text-xs font-semibold text-emerald-300">Dívida foi perdoada</button>}</div></details></article>)}</div>}
    {!error&&projected.length>0&&<div className="mt-4 space-y-2"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Entre vocês · tendência</p>{projected.map(row=><article key={`projected-${row.debtor_member_id}-${row.creditor_member_id}`} className="rounded-2xl border border-dashed border-slate-800 p-4"><div className="flex justify-between gap-3"><div><b>{memberName(row.creditor_member_id)} pode ter a receber de {memberName(row.debtor_member_id)}</b><p className="text-xs text-slate-500">É uma previsão ligada a compromissos futuros. Ainda não é uma diferença realizada entre vocês.</p></div><strong className="whitespace-nowrap text-slate-400">{money(projectedNet(row))}</strong></div><details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer font-semibold text-slate-400">Ver compromissos que podem gerar esta diferença</summary><ul className="mt-2 space-y-2">{eventsFor(row,'projected').map(event=><li key={event.id} className="flex justify-between gap-3"><span>{eventLabel(event)} · {new Date(`${event.financial_date}T12:00:00`).toLocaleDateString('pt-BR')}</span><strong>{money(event.amount)}</strong></li>)}</ul></details></article>)}</div>}
    {!error&&completedSettlements.length>0&&<div className="mt-5"><div className="mb-2 flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Histórico entre vocês</p><p className="mt-1 text-xs text-slate-600">Movimentos neutros que alteraram a posição entre vocês sem virar renda ou gasto.</p></div><span className="rounded-full bg-slate-800 px-2 py-1 text-[10px] font-bold text-slate-400">últimos {completedSettlements.length}</span></div><div className="space-y-2">{completedSettlements.map(event=><article key={event.id} className="rounded-2xl border border-slate-800 bg-slate-900/45 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-semibold text-slate-200">Movimento entre vocês</p><p className="mt-1 text-xs text-slate-500">{event.kind==='adjustment'&&event.source_money_movement_id?`${memberName(event.creditor_member_id)} transferiu para ${memberName(event.debtor_member_id)}`:`${memberName(event.debtor_member_id)} pagou ${memberName(event.creditor_member_id)}`} · {new Date(`${event.financial_date}T12:00:00`).toLocaleDateString('pt-BR')}</p>{event.notes?.trim()&&<p className="mt-1 truncate text-[11px] text-slate-600">{event.notes}</p>}</div><strong className="whitespace-nowrap text-sm text-cyan-200">{money(event.amount)}</strong></div></article>)}</div></div>}
  </section>;
}
