import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { AlertTriangle, LoaderCircle } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { listOpenThirdPartyObligations, writeOffThirdPartyReceivable, type ThirdPartyObligation } from '../../finance/thirdPartyObligations.js';

const formatMoney=(value:unknown)=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const normalizeAmount=(value:string)=>value.trim().replace(/\./g,'').replace(',','.');
const localDate=()=>{const now=new Date();const offset=now.getTimezoneOffset();return new Date(now.getTime()-offset*60_000).toISOString().slice(0,10);};

export function ThirdPartyReceivableWriteOff({onBack,initialObligationId}:{onBack:()=>void;initialObligationId?:string}){
  const{household,householdMembers}=useSupabaseAuth();
  const[receivables,setReceivables]=useState<ThirdPartyObligation[]>([]); const[obligationId,setObligationId]=useState(''); const[amount,setAmount]=useState(''); const[lossDate,setLossDate]=useState(localDate()); const[percentages,setPercentages]=useState<Record<string,string>>({}); const[notes,setNotes]=useState(''); const[loading,setLoading]=useState(true); const[saving,setSaving]=useState(false); const[loadError,setLoadError]=useState<string|null>(null); const[error,setError]=useState<string|null>(null); const[success,setSuccess]=useState<string|null>(null);
  const clearLoadedContext=()=>{setReceivables([]);setObligationId('');setAmount('');setPercentages({});};
  const load=async()=>{if(!supabase||!household)return;setLoading(true);setLoadError(null);setError(null);try{const rows=await listOpenThirdPartyObligations(supabase,household.id);const next=rows.filter(row=>row.kind==='receivable');setReceivables(next);if(initialObligationId){const target=next.find(row=>row.id===initialObligationId);if(target){setObligationId(target.id);setAmount(target.outstanding_amount.toFixed(2).replace('.',','));setPercentages({});}}}catch{clearLoadedContext();setLoadError('Não foi possível conferir os valores a receber. Nenhuma perda será registrada até uma nova leitura válida.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[household?.id,initialObligationId]);
  const selected=useMemo(()=>receivables.find(row=>row.id===obligationId),[receivables,obligationId]);
  const percentageTotal=useMemo(()=>householdMembers.reduce((sum,member)=>sum+(Number((percentages[member.id]??'0').replace(',','.'))||0),0),[householdMembers,percentages]);
  const chooseReceivable=(id:string)=>{setObligationId(id);const row=receivables.find(item=>item.id===id);setAmount(row?row.outstanding_amount.toFixed(2).replace('.',','):'');setPercentages({});setError(null);setSuccess(null);};
  const setAllTo=(memberId:string)=>{const next:Record<string,string>={};for(const member of householdMembers)next[member.id]=member.id===memberId?'100':'0';setPercentages(next);};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(loadError||loading){setError('Confira novamente os valores a receber antes de continuar.');return;}if(!supabase||!household||!selected)return;const normalized=normalizeAmount(amount);const numeric=Number(normalized);if(!Number.isFinite(numeric)||numeric<=0){setError('Informe quanto vocês não vão mais receber.');return;}if(numeric>selected.outstanding_amount){setError('Esse valor não pode ser maior do que ainda falta receber.');return;}const allocations=householdMembers.map(member=>({memberId:member.id,percentage:Number((percentages[member.id]??'0').replace(',','.'))||0})).filter(item=>item.percentage>0);if(Math.abs(percentageTotal-100)>0.000001){setError('Defina quem assume essa perda. Os percentuais precisam totalizar 100%.');return;}setSaving(true);setError(null);setSuccess(null);try{await writeOffThirdPartyReceivable(supabase,{householdId:household.id,obligationId:selected.id,amount:normalized,lossDate,allocations,notes});setSuccess('Pronto. O Casa reduziu o valor que ainda seria recebido e registrou a perda. Nenhum dinheiro entrou ou saiu de uma conta.');setObligationId('');setAmount('');setPercentages({});setNotes('');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível registrar que esse valor não será recebido.');}finally{setSaving(false);}};
  return <div className="space-y-4"><button type="button" onClick={onBack} className="text-sm font-semibold text-blue-300">← Voltar aos valores com pessoas</button>{loading?<LoaderCircle className="mx-auto h-6 w-6 animate-spin"/>:loadError?<div className="rounded-2xl border border-rose-900 bg-rose-950/30 p-4"><p role="alert" className="text-sm text-rose-200">{loadError}</p><button type="button" onClick={()=>void load()} className="mt-3 min-h-11 rounded-xl border border-rose-800 px-3 text-sm font-semibold text-rose-200">Tentar novamente</button></div>:<form onSubmit={submit} className="space-y-4 rounded-2xl border border-rose-900/70 bg-rose-950/20 p-4">
    <div><h2 className="font-bold">Valor que não será recebido</h2><p className="mt-1 text-sm text-slate-400">Use quando alguém realmente devia para a Casa, mas vocês decidiram que parte ou todo esse valor não será mais recebido. Se o cadastro estava errado desde o começo, use a correção de cadastro.</p></div>
    <div className="rounded-xl border border-amber-900 bg-amber-950/20 p-3 text-xs text-amber-200"><AlertTriangle className="mr-1 inline h-4 w-4"/><strong>Isso registra uma perda:</strong> vocês estão abrindo mão de um valor que a Casa tinha direito de receber. Nenhum dinheiro sai de uma conta, porque ele ainda não tinha entrado.</div>
    <label className="block text-sm">Qual valor vocês não vão mais receber?<select value={obligationId} onChange={event=>chooseReceivable(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">Selecione</option>{receivables.map(item=><option key={item.id} value={item.id}>A receber de {item.counterparty_name} · {formatMoney(item.outstanding_amount)}</option>)}</select></label>
    {selected&&<div className="rounded-xl bg-slate-950 p-3 text-sm"><p className="font-semibold">{selected.description}</p><p className="mt-1 text-slate-400">Valor original: {formatMoney(selected.original_amount)} · já resolvido: {formatMoney(selected.settled_amount)} · ainda falta receber: <strong className="text-amber-200">{formatMoney(selected.outstanding_amount)}</strong></p></div>}
    {selected&&<><label className="block text-sm">Quanto vocês não vão mais receber?<input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="block text-sm">Quando vocês decidiram isso?<input type="date" value={lossDate} onChange={event=>setLossDate(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><fieldset className="space-y-3 rounded-xl border border-slate-800 p-3"><legend className="px-1 text-sm font-semibold">De quem é essa perda?</legend><p className="text-xs text-slate-400">Escolha como essa perda fica dividida entre vocês. Isso é independente de quem criou ou esperava receber o valor.</p>{householdMembers.map(member=><div key={member.id} className="grid grid-cols-[1fr_7rem] items-center gap-3"><button type="button" onClick={()=>setAllTo(member.id)} className="text-left text-sm text-blue-300">100% {member.display_name}</button><label className="text-xs text-slate-400"><span className="sr-only">Percentual de {member.display_name}</span><input inputMode="decimal" value={percentages[member.id]??''} onChange={event=>setPercentages(current=>({...current,[member.id]:event.target.value}))} className="w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-right" placeholder="0"/>%</label></div>)}<p className={`text-right text-xs font-semibold ${Math.abs(percentageTotal-100)<0.000001?'text-emerald-300':'text-amber-300'}`}>Total: {percentageTotal.toLocaleString('pt-BR')}%</p></fieldset><label className="block text-sm">Por que não será recebido?<textarea value={notes} onChange={event=>setNotes(event.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Ex.: pessoa não tem mais condição de pagar e decidimos encerrar a cobrança"/></label></>}
    {receivables.length===0&&<p className="rounded-xl bg-slate-950 p-3 text-sm text-slate-400">Não há valores a receber em aberto.</p>}{error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}{success&&<p role="status" className="text-sm text-emerald-300">{success}</p>}
    <button type="submit" disabled={saving||!selected} className="min-h-12 w-full rounded-xl bg-rose-700 font-bold disabled:opacity-50">{saving?'Registrando…':'Confirmar que não será recebido'}</button>
  </form>}</div>;
}
