import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { HandHeart, LoaderCircle } from 'lucide-react';
import { useSupabaseAuth } from '../../context/SupabaseAuthContext.js';
import { supabase } from '../../lib/supabase.js';
import { forgiveThirdPartyPayable, listOpenThirdPartyObligations, type ThirdPartyObligation } from '../../finance/thirdPartyObligations.js';

const money=(value:unknown)=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const normalizeAmount=(value:string)=>value.trim().replace(/\./g,'').replace(',','.');
const localDate=()=>{const now=new Date();const offset=now.getTimezoneOffset();return new Date(now.getTime()-offset*60_000).toISOString().slice(0,10);};

export function ThirdPartyPayableForgiveness({onBack}:{onBack:()=>void}){
  const{household,householdMembers}=useSupabaseAuth();
  const[payables,setPayables]=useState<ThirdPartyObligation[]>([]);const[obligationId,setObligationId]=useState('');const[amount,setAmount]=useState('');const[forgivenDate,setForgivenDate]=useState(localDate());const[percentages,setPercentages]=useState<Record<string,string>>({});const[notes,setNotes]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[loadError,setLoadError]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[success,setSuccess]=useState<string|null>(null);
  const clearLoadedContext=()=>{setPayables([]);setObligationId('');setAmount('');setPercentages({});};
  const load=async()=>{if(!supabase||!household)return;setLoading(true);setLoadError(null);setError(null);try{const rows=await listOpenThirdPartyObligations(supabase,household.id);setPayables(rows.filter(row=>row.kind==='payable'));}catch{clearLoadedContext();setLoadError('Não foi possível conferir os valores que a Casa deve. Nenhum perdão será registrado até uma nova leitura válida.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[household?.id]);
  const selected=useMemo(()=>payables.find(row=>row.id===obligationId),[payables,obligationId]);
  const percentageTotal=useMemo(()=>householdMembers.reduce((sum,member)=>sum+(Number((percentages[member.id]??'0').replace(',','.'))||0),0),[householdMembers,percentages]);
  const choose=(id:string)=>{setObligationId(id);const row=payables.find(item=>item.id===id);setAmount(row?row.outstanding_amount.toFixed(2).replace('.',','):'');setPercentages({});setError(null);setSuccess(null);};
  const setAllTo=(memberId:string)=>{const next:Record<string,string>={};for(const member of householdMembers)next[member.id]=member.id===memberId?'100':'0';setPercentages(next);};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(loadError||loading){setError('Confira novamente os valores a pagar antes de continuar.');return;}if(!supabase||!household||!selected)return;const normalized=normalizeAmount(amount);const numeric=Number(normalized);if(!Number.isFinite(numeric)||numeric<=0){setError('Informe quanto deixou de ser cobrado.');return;}if(numeric>selected.outstanding_amount){setError('Esse valor não pode ser maior do que ainda falta pagar.');return;}if(Math.abs(percentageTotal-100)>0.000001){setError('Defina para quem fica esse benefício. Os percentuais precisam totalizar 100%.');return;}const allocations=householdMembers.map(member=>({memberId:member.id,percentage:Number((percentages[member.id]??'0').replace(',','.'))||0})).filter(item=>item.percentage>0);setSaving(true);setError(null);setSuccess(null);try{await forgiveThirdPartyPayable(supabase,{householdId:household.id,obligationId:selected.id,amount:normalized,forgivenDate,allocations,notes});setSuccess('Pronto. O valor que a Casa ainda devia diminuiu sem nenhum pagamento e sem movimentar uma conta. Como uma dívida real deixou de existir, o Casa registra esse benefício econômico separadamente.');setObligationId('');setAmount('');setPercentages({});setNotes('');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível registrar que esse valor foi perdoado.');}finally{setSaving(false);}};
  return <div className="space-y-4"><button type="button" onClick={onBack} className="text-sm font-semibold text-blue-300">← Voltar aos ajustes</button>{loading?<LoaderCircle className="mx-auto h-6 w-6 animate-spin"/>:loadError?<div className="rounded-2xl border border-rose-900 bg-rose-950/30 p-4"><p role="alert" className="text-sm text-rose-200">{loadError}</p><button type="button" onClick={()=>void load()} className="mt-3 min-h-11 rounded-xl border border-rose-800 px-3 text-sm font-semibold text-rose-200">Tentar novamente</button></div>:<form onSubmit={submit} className="space-y-4 rounded-2xl border border-emerald-900/70 bg-emerald-950/20 p-4">
    <div><h2 className="font-bold">Dívida que foi perdoada</h2><p className="mt-1 text-sm text-slate-400">Use quando a Casa realmente devia para alguém, mas essa pessoa decidiu que parte ou todo o valor não precisa mais ser pago.</p></div>
    <div className="rounded-xl border border-blue-900 bg-blue-950/30 p-3 text-xs text-blue-200"><HandHeart className="mr-1 inline h-4 w-4"/><strong>Nenhum pagamento acontece aqui:</strong> o valor devido diminui, mas nenhuma conta é debitada. Como a Casa deixou de dever um valor real, existe um benefício econômico sem entrada de dinheiro.</div>
    <label className="block text-sm">Qual valor foi perdoado?<select value={obligationId} onChange={event=>choose(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">Selecione</option>{payables.map(item=><option key={item.id} value={item.id}>A pagar para {item.counterparty_name} · {money(item.outstanding_amount)}</option>)}</select></label>
    {selected&&<div className="rounded-xl bg-slate-950 p-3 text-sm"><p className="font-semibold">{selected.description}</p><p className="mt-1 text-slate-400">Valor original: {money(selected.original_amount)} · já resolvido: {money(selected.settled_amount)} · ainda falta pagar: <strong className="text-amber-200">{money(selected.outstanding_amount)}</strong></p></div>}
    {selected&&<><label className="block text-sm">Quanto não precisa mais ser pago?<input inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="block text-sm">Quando isso foi combinado?<input type="date" value={forgivenDate} onChange={event=>setForgivenDate(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><fieldset className="space-y-3 rounded-xl border border-slate-800 p-3"><legend className="px-1 text-sm font-semibold">Para quem fica esse benefício?</legend><p className="text-xs text-slate-400">Escolha como o benefício de não precisar pagar esse valor fica dividido entre vocês. Não usamos comprador, titular de conta ou quem pagaria como atalho.</p>{householdMembers.map(member=><div key={member.id} className="grid grid-cols-[1fr_7rem] items-center gap-3"><button type="button" onClick={()=>setAllTo(member.id)} className="text-left text-sm text-blue-300">100% {member.display_name}</button><label className="text-xs text-slate-400"><span className="sr-only">Percentual de {member.display_name}</span><input inputMode="decimal" value={percentages[member.id]??''} onChange={event=>setPercentages(current=>({...current,[member.id]:event.target.value}))} className="w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-right" placeholder="0"/>%</label></div>)}<p className={`text-right text-xs font-semibold ${Math.abs(percentageTotal-100)<0.000001?'text-emerald-300':'text-amber-300'}`}>Total: {percentageTotal.toLocaleString('pt-BR')}%</p></fieldset><label className="block text-sm">Por que foi perdoado? (opcional)<textarea value={notes} onChange={event=>setNotes(event.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Ex.: a pessoa decidiu perdoar o saldo restante"/></label></>}
    {payables.length===0&&<p className="rounded-xl bg-slate-950 p-3 text-sm text-slate-400">Não há valores a pagar em aberto.</p>}{error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}{success&&<p role="status" className="text-sm text-emerald-300">{success}</p>}
    <button type="submit" disabled={saving||!selected} className="min-h-12 w-full rounded-xl bg-emerald-700 font-bold disabled:opacity-50">{saving?'Registrando…':'Confirmar dívida perdoada'}</button>
  </form>}</div>;
}
