import React, { useState } from 'react';
import { CreditCard, Edit2, Plus, Power, X } from 'lucide-react';
import { useAuth } from '../../context/AuthContext.js';
import { ApiService } from '../../services/api.js';
import type { Account, Card, User } from '../../types/index.js';
import { triggerHaptic } from '../../utils/haptics.js';

interface Props { cards: Card[]; accounts: Account[]; householdId: string; currentUser: User; onRefresh: () => void; }
export const CardsManager: React.FC<Props> = ({ cards, accounts, householdId, currentUser, onRefresh }) => {
  const { householdMembers } = useAuth();
  const [editing, setEditing] = useState<Card | null>(null); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ name: '', institution: '', owner: currentUser.id, limit: '', closing: '10', due: '17', account: '', color: '#2563eb' });
  const show = (card?: Card) => { setEditing(card ?? null); setForm(card ? { name: card.name, institution: card.institution, owner: card.owner_user_id, limit: String(card.credit_limit), closing: String(card.closing_day), due: String(card.due_day), account: card.default_payment_account_id ?? '', color: card.color } : { name: '', institution: '', owner: currentUser.id, limit: '', closing: '10', due: '17', account: '', color: '#2563eb' }); setOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const payload: Partial<Card> = { name: form.name.trim(), institution: form.institution.trim(), owner_user_id: form.owner, credit_limit: Number(form.limit), closing_day: Number(form.closing), due_day: Number(form.due), default_payment_account_id: form.account || null, color: form.color, card_type: 'credit' }; try { if (editing) await ApiService.updateCard(householdId, currentUser.id, editing.id, payload); else await ApiService.createCard(householdId, currentUser.id, payload); triggerHaptic('success'); setOpen(false); onRefresh(); } finally { setSaving(false); } };
  const deactivate = async () => { if (!editing || !confirm('Desativar este cartão? Compras e faturas anteriores serão preservadas.')) return; await ApiService.deleteCard(householdId, currentUser.id, editing.id); setOpen(false); onRefresh(); };
  const field = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  return <div className="space-y-4"><header className="flex justify-between gap-3"><div><h2 className="text-base font-bold">Cartões de crédito</h2><p className="text-xs text-slate-400">Cadastre regras e a conta padrão de pagamento.</p></div><button onClick={() => show()} className="min-h-11 px-3 rounded-xl bg-blue-600 text-xs font-bold flex items-center gap-1"><Plus className="w-4 h-4"/>Cadastrar</button></header>
  <div className="space-y-2">{cards.map(card => <article key={card.id} className="p-4 rounded-2xl border border-slate-800 bg-slate-900 flex gap-3 items-center"><div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{backgroundColor: card.color}}><CreditCard className="w-5 h-5"/></div><div className="flex-1 min-w-0"><h3 className="text-sm font-bold truncate">{card.name}</h3><p className="text-xs text-slate-400 truncate">{card.institution} · {householdMembers.find(m => m.user_id === card.owner_user_id)?.user?.name ?? 'Titular'} · fecha dia {card.closing_day} · vence dia {card.due_day}</p></div><button aria-label={`Editar ${card.name}`} onClick={() => show(card)} className="min-w-11 min-h-11 rounded-xl border border-slate-700 flex items-center justify-center"><Edit2 className="w-4 h-4"/></button></article>)}</div>
  {open && <div className="fixed inset-0 z-50 bg-black/70 p-4 flex items-end sm:items-center justify-center"><form onSubmit={save} className="w-full max-w-md max-h-[90vh] overflow-y-auto rounded-3xl border border-slate-700 bg-slate-900 p-5 space-y-3"><div className="flex justify-between"><h3 className="font-bold">{editing ? 'Editar cartão' : 'Cadastrar cartão'}</h3><button type="button" onClick={() => setOpen(false)} className="min-w-11 min-h-11"><X className="mx-auto"/></button></div>
  {[['name','Nome'],['institution','Instituição'],['limit','Limite'],['closing','Dia de fechamento'],['due','Dia de vencimento']].map(([key,label]) => <label key={key} className="block text-xs text-slate-300">{label}<input required type={['limit','closing','due'].includes(key) ? 'number' : 'text'} min={key === 'limit' ? 0 : 1} max={key === 'closing' || key === 'due' ? 31 : undefined} value={form[key as keyof typeof form]} onChange={e => field(key as keyof typeof form,e.target.value)} className="mt-1 p-3 w-full rounded-xl bg-slate-800"/></label>)}
  <label className="block text-xs">Titular<select value={form.owner} onChange={e=>field('owner',e.target.value)} className="mt-1 p-3 w-full rounded-xl bg-slate-800">{householdMembers.filter(m=>m.is_active).map(m=><option key={m.user_id} value={m.user_id}>{m.user?.name}</option>)}</select></label>
  <label className="block text-xs">Conta padrão de pagamento<select value={form.account} onChange={e=>field('account',e.target.value)} className="mt-1 p-3 w-full rounded-xl bg-slate-800"><option value="">Nenhuma</option>{accounts.filter(a=>['checking','savings'].includes(a.account_type)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
  <label className="block text-xs">Cor<input type="color" value={form.color} onChange={e=>field('color',e.target.value)} className="mt-1 w-full h-11 rounded-xl bg-slate-800"/></label><div className="flex gap-2">{editing&&<button type="button" onClick={deactivate} className="px-3 rounded-xl bg-rose-950 text-rose-300"><Power/></button>}<button disabled={saving} className="flex-1 min-h-11 rounded-xl bg-blue-600 font-bold">{saving?'Salvando…':'Salvar cadastro'}</button></div></form></div>}</div>;
};
